[package]
name = "action_wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
processes = { path = "../../common/processes" }

clap.workspace = true
anyhow.workspace = true
libc.workspace = true
tempfile.workspace = true
