[package]
name = "action_wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrome-trace = { path = "../../common/chrome-trace" }
cliutil = { path = "../../common/cliutil" }
fileutil = { path = "../../common/fileutil" }
processes = { path = "../../common/processes" }

anyhow.workspace = true
clap.workspace = true
nix.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[dev-dependencies]
libc.workspace = true
regex.workspace = true
tempfile.workspace = true
