load("//bazel/ebuild:defs.bzl", "binary_package")

binary_package(
    name = "gcc-libs",
    src = "@arm64_generic_gcc_libs_10_2_0_r4//file",
    visibility = ["//visibility:public"],
)

binary_package(
    name = "libcxx",
    src = "@arm64_generic_libcxx_15_0_pre458507_r5//file",
    visibility = ["//visibility:public"],
)

binary_package(
    name = "llvm-libunwind",
    src = "@arm64_generic_llvm_libunwind_15_0_pre458507_r4//file",
    visibility = ["//visibility:public"],
)
