load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "naming",
    srcs = ["check.go"],
    importpath = "cros.local/rules_ebuild/ebuild/private/common/standard/naming",
    visibility = ["//visibility:public"],
    deps = ["//ebuild/private/common/standard/version"],
)
