[package]
name = "sdk_update"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binarypackage = { path = "../../common/portage/binarypackage" }
fileutil = { path = "../../common/fileutil" }
makechroot = { path = "../../common/makechroot" }
mountsdk = { path = "../../common/mountsdk" }
tar = { path = "../../common/tar" }

anyhow.workspace = true
clap.workspace = true
runfiles.workspace = true
tempfile.workspace = true
