[package]
name = "sdk_update"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fileutil = { path = "../../common/fileutil" }
makechroot = { path = "../../common/makechroot" }
processes = { path = "../../common/processes" }
run_in_container_lib = { path = "../../common/run_in_container_lib" }
tar = { path = "../../common/tar" }

anyhow.workspace = true
clap.workspace = true
runfiles.workspace = true
tempfile.workspace = true
