load("//ebuild:defs.bzl", "ebuild")

ebuild(
    name = "elt-patches",
    src = "elt-patches-20210924.ebuild",
    category = "app-portage",
    distfiles = {
        "@elt-patches_20210924//file": "elt-patches-20210924.tar.xz",
    },
)
