load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Google-BSD

bzl_library(
    name = "bzl_lib",
    srcs = glob(["**/*.bzl"]),
)
