[package]
name = "extract_interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cliutil = { path = "../../common/cliutil" }
binarypackage = { path = "../../common/portage/binarypackage" }
processes = { path = "../../common/processes" }

anyhow.workspace = true
clap.workspace = true
runfiles.workspace = true
tar.workspace = true
zstd.workspace = true

[dev-dependencies]
fileutil = { path = "../../common/fileutil" }
