[package]
name = "tar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fileutil = { path = "../fileutil" }

anyhow.workspace = true
tar.workspace = true
walkdir.workspace = true
