[package]
name = "makechroot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cliutil = { path = "../cliutil" }
fileutil = { path = "../fileutil" }
durabletree = { path = "../durabletree" }

anyhow.workspace = true
itertools.workspace = true
path-absolutize.workspace = true
serde.workspace = true
walkdir.workspace = true

[dev-dependencies]
runfiles.workspace = true
tempfile.workspace = true
