[package]
name = "extract_package_from_manifest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extract_package_from_manifest_package = { path = "../package" }
cliutil = { path = "../../../common/cliutil" }

anyhow.workspace = true
clap.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
