#!/bin/bash -x
#
# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -eu -o pipefail

SCRIPT_DIR="$(dirname -- "${BASH_SOURCE[0]}")"

# Rewrites the paths in the patches generated by `git format-patch` so that we
# can apply them to the installed portage version.
find "${SCRIPT_DIR}" -name "*.patch" -exec sed -i -E \
	-e 's| ([ab])/lib/| \1/usr/PYTHON_LIBDIR/PYTHON_VERSION/site-packages/|g' \
	-e 's| ([ab])/bin/| \1/usr/lib/portage/PYTHON_VERSION/|g' \
	'{}' \+
