# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

HOST = "host"
TARGET = "target"

PACKAGE_TO_CORE_COUNT = {
    "acct-group/arc-keymintd": {TARGET: 2},
    "acct-group/audio": {HOST: 2, TARGET: 2},
    "acct-group/bluetooth-audio": {TARGET: 2},
    "acct-group/bpf-access": {TARGET: 2},
    "acct-group/cdrom": {HOST: 4, TARGET: 2},
    "acct-group/chronos": {HOST: 4, TARGET: 2},
    "acct-group/cras": {TARGET: 2},
    "acct-group/cros_healthd": {TARGET: 2},
    "acct-group/dhcp": {HOST: 4, TARGET: 2},
    "acct-group/dialout": {HOST: 2, TARGET: 2},
    "acct-group/disk": {HOST: 4, TARGET: 2},
    "acct-group/dnsmasq": {TARGET: 2},
    "acct-group/fbpreprocessor": {HOST: 2, TARGET: 2},
    "acct-group/fbpreprocessor-user-access": {HOST: 4, TARGET: 4},
    "acct-group/feature-writers": {TARGET: 2},
    "acct-group/fwupd": {HOST: 4, TARGET: 2},
    "acct-group/input": {HOST: 4, TARGET: 2},
    "acct-group/kmem": {HOST: 4, TARGET: 2},
    "acct-group/kvm": {HOST: 2, TARGET: 2},
    "acct-group/lp": {HOST: 4, TARGET: 2},
    "acct-group/minios": {TARGET: 2},
    "acct-group/netperf": {HOST: 4, TARGET: 2},
    "acct-group/node_exporter": {TARGET: 2},
    "acct-group/pcap": {TARGET: 2},
    "acct-group/session_manager": {TARGET: 2},
    "acct-group/sound_card_init": {TARGET: 2},
    "acct-group/sshd": {TARGET: 2},
    "acct-group/tape": {HOST: 4, TARGET: 2},
    "acct-group/tty": {HOST: 2, TARGET: 2},
    "acct-group/utmp": {TARGET: 2},
    "acct-group/video": {HOST: 4, TARGET: 4},
    "acct-user/arc-keymintd": {TARGET: 2},
    "acct-user/cfm-firmware-updaters": {HOST: 4, TARGET: 2},
    "acct-user/chronos": {HOST: 2, TARGET: 2},
    "acct-user/cras": {TARGET: 2},
    "acct-user/cros_healthd": {HOST: 4, TARGET: 2},
    "acct-user/dhcp": {HOST: 4, TARGET: 2},
    "acct-user/dnsmasq": {TARGET: 2},
    "acct-user/fbpreprocessor": {TARGET: 2},
    "acct-user/feature-writers": {TARGET: 2},
    "acct-user/fwupd": {HOST: 2, TARGET: 2},
    "acct-user/minios": {TARGET: 4},
    "acct-user/netperf": {HOST: 4, TARGET: 2},
    "acct-user/node_exporter": {TARGET: 2},
    "acct-user/pcap": {TARGET: 2},
    "acct-user/session_manager": {TARGET: 2},
    "acct-user/sound_card_init": {TARGET: 2},
    "acct-user/sshd": {TARGET: 2},
    "app-accessibility/brltty": {TARGET: 2},
    "app-accessibility/espeak-ng": {TARGET: 2},
    "app-accessibility/facegaze-assets": {TARGET: 2},
    "app-accessibility/googletts": {TARGET: 2},
    "app-accessibility/pumpkin": {TARGET: 2},
    "app-accessibility/screen-ai": {TARGET: 2},
    "app-admin/eselect": {HOST: 4},
    "app-admin/rsyslog": {TARGET: 2},
    "app-admin/sudo": {TARGET: 4},
    "app-admin/sysstat": {TARGET: 2},
    "app-alternatives/awk": {HOST: 4, TARGET: 2},
    "app-alternatives/bc": {TARGET: 2},
    "app-alternatives/gzip": {HOST: 2, TARGET: 2},
    "app-alternatives/tar": {HOST: 2, TARGET: 2},
    "app-alternatives/yacc": {HOST: 2},
    "app-arch/brotli": {TARGET: 2},
    "app-arch/bzip2": {HOST: 2, TARGET: 2},
    "app-arch/cabextract": {HOST: 2},
    "app-arch/gcab": {HOST: 2, TARGET: 2},
    "app-arch/gzip": {HOST: 2, TARGET: 2},
    "app-arch/lbzip2": {TARGET: 2},
    "app-arch/libarchive": {HOST: 2, TARGET: 2},
    "app-arch/lz4": {HOST: 2, TARGET: 4},
    "app-arch/makeself": {HOST: 4},
    "app-arch/pigz": {HOST: 2, TARGET: 2},
    "app-arch/sharutils": {TARGET: 2},
    "app-arch/snappy": {TARGET: 2},
    "app-arch/tar": {HOST: 4, TARGET: 2},
    "app-arch/unrar": {TARGET: 8},
    "app-arch/unzip": {HOST: 2, TARGET: 4},
    "app-arch/xz-utils": {HOST: 2, TARGET: 2},
    "app-arch/zip": {HOST: 4, TARGET: 2},
    "app-arch/zstd": {HOST: 4, TARGET: 2},
    "app-benchmarks/blktests": {TARGET: 4},
    "app-benchmarks/blogbench": {TARGET: 2},
    "app-benchmarks/bootchart": {TARGET: 2},
    "app-benchmarks/libc-bench": {TARGET: 2},
    "app-benchmarks/lmbench": {TARGET: 2},
    "app-benchmarks/microbenchmarks": {TARGET: 2},
    "app-benchmarks/pjdfstest": {TARGET: 2},
    "app-benchmarks/stress-ng": {TARGET: 2},
    "app-crypt/gnupg": {TARGET: 2},
    "app-crypt/mit-krb5": {HOST: 2, TARGET: 2},
    "app-crypt/nss": {HOST: 2, TARGET: 2},
    "app-crypt/p11-kit": {HOST: 2},
    "app-crypt/pinentry": {TARGET: 2},
    "app-crypt/rhash": {HOST: 2},
    "app-doc/xmltoman": {HOST: 4},
    "app-editors/nano": {HOST: 2, TARGET: 2},
    "app-editors/neatvi": {TARGET: 2},
    "app-editors/qemacs": {TARGET: 2},
    "app-editors/vim": {TARGET: 2},
    "app-editors/vim-core": {TARGET: 4},
    "app-emulation/parallels-desktop": {TARGET: 2},
    "app-emulation/qemu": {HOST: 16},
    "app-eselect/eselect-iptables": {HOST: 2},
    "app-eselect/eselect-java": {HOST: 2},
    "app-eselect/eselect-vi": {TARGET: 2},
    "app-i18n/chinese-input": {TARGET: 2},
    "app-i18n/chromeos-cangjie": {TARGET: 2},
    "app-i18n/chromeos-hangul": {TARGET: 2},
    "app-i18n/chromeos-keyboards": {TARGET: 2},
    "app-i18n/chromeos-pinyin": {TARGET: 2},
    "app-i18n/chromeos-xkb": {TARGET: 2},
    "app-i18n/chromeos-zhuyin": {TARGET: 2},
    "app-i18n/hangul-input": {TARGET: 2},
    "app-i18n/input-tools": {TARGET: 2},
    "app-i18n/input-tools-nacl": {TARGET: 2},
    "app-i18n/japanese-input": {TARGET: 2},
    "app-i18n/keyboard-input": {TARGET: 2},
    "app-i18n/nacl-mozc": {TARGET: 2},
    "app-metrics/node_exporter": {TARGET: 4},
    "app-misc/c_rehash": {HOST: 4, TARGET: 4},
    "app-misc/ca-certificates": {HOST: 2, TARGET: 2},
    "app-misc/edid-decode": {TARGET: 2},
    "app-misc/eglinfo": {TARGET: 2},
    "app-misc/evtest": {TARGET: 2},
    "app-misc/figlet": {TARGET: 2},
    "app-misc/jq": {HOST: 2, TARGET: 2},
    "app-misc/pax-utils": {HOST: 2, TARGET: 2},
    "app-misc/screen": {TARGET: 2},
    "app-misc/tmux": {TARGET: 2},
    "app-misc/utouch-evemu": {TARGET: 2},
    "app-mobilephone/dfu-util": {TARGET: 2},
    "app-portage/elt-patches": {HOST: 2},
    "app-portage/portage-utils": {HOST: 2, TARGET: 2},
    "app-shells/bash": {HOST: 2, TARGET: 2},
    "app-shells/dash": {TARGET: 2},
    "app-text/build-docbook-catalog": {HOST: 2},
    "app-text/docbook-xml-dtd": {HOST: 2},
    "app-text/docbook-xsl-stylesheets": {HOST: 2},
    "app-text/ghostscript-gpl": {TARGET: 4},
    "app-text/libpaper": {TARGET: 2},
    "app-text/poppler": {TARGET: 16},
    "app-text/qpdf": {TARGET: 16},
    "app-text/sgml-common": {HOST: 2},
    "app-text/tree": {TARGET: 2},
    "app-text/xmlto": {HOST: 2},
    "brillo-base/libsparse": {HOST: 4},
    "chromeos-base/android-container-pi": {TARGET: 2},
    "chromeos-base/android-sdk": {HOST: 2},
    "chromeos-base/android-vm-tm": {TARGET: 2},
    "chromeos-base/aosp-frameworks-base-proto": {TARGET: 2},
    "chromeos-base/arc-adbd": {TARGET: 8},
    "chromeos-base/arc-apk-cache": {TARGET: 4},
    "chromeos-base/arc-base": {TARGET: 2},
    "chromeos-base/arc-first-api-level": {TARGET: 2},
    "chromeos-base/arc-host-clock-service": {TARGET: 2},
    "chromeos-base/arc-keymaster": {TARGET: 8},  # nocheck
    "chromeos-base/arc-keymint": {TARGET: 8},
    "chromeos-base/arc-media-profiles-default": {TARGET: 2},
    "chromeos-base/arc-setup": {TARGET: 8},
    "chromeos-base/arc-sslh-init": {TARGET: 2},
    "chromeos-base/arcvm-boot-notification-server": {TARGET: 4},
    "chromeos-base/arcvm-codec-chipset-adl": {TARGET: 2},
    "chromeos-base/arcvm-common-scripts": {TARGET: 2},
    "chromeos-base/arcvm-media-sharing-services": {TARGET: 2},
    "chromeos-base/arcvm-mojo-proxy": {TARGET: 4},
    "chromeos-base/attestation": {TARGET: 8},
    "chromeos-base/attestation-client": {TARGET: 2},
    "chromeos-base/audiotest": {TARGET: 2},
    "chromeos-base/autotest": {TARGET: 2},
    "chromeos-base/autotest-all": {TARGET: 2},
    "chromeos-base/autotest-capability-amd64-generic": {TARGET: 2},
    "chromeos-base/autotest-capability-chipset-adl": {TARGET: 2},
    "chromeos-base/autotest-capability-default": {TARGET: 2},
    "chromeos-base/autotest-cheets-libs": {TARGET: 2},
    "chromeos-base/autotest-chrome": {TARGET: 2},
    "chromeos-base/autotest-client": {TARGET: 2},
    "chromeos-base/autotest-deps": {TARGET: 2},
    "chromeos-base/autotest-deps-policy": {TARGET: 2},
    "chromeos-base/autotest-deps-touchpad": {TARGET: 2},
    "chromeos-base/autotest-private": {TARGET: 2},
    "chromeos-base/autotest-private-all": {TARGET: 2},
    "chromeos-base/autotest-private-libs": {TARGET: 2},
    "chromeos-base/autotest-private-tests-echoprivate": {TARGET: 2},
    "chromeos-base/autotest-private-tests-pagecycler": {TARGET: 4},
    "chromeos-base/autotest-server-tests": {TARGET: 2},
    "chromeos-base/autotest-server-tests-bluetooth": {TARGET: 2},
    "chromeos-base/autotest-server-tests-shill": {TARGET: 2},
    "chromeos-base/autotest-server-tests-tast": {TARGET: 2},
    "chromeos-base/autotest-server-tests-telemetry": {TARGET: 2},
    "chromeos-base/autotest-tests": {TARGET: 2},
    "chromeos-base/autotest-tests-arc-public": {TARGET: 2},
    "chromeos-base/autotest-tests-audio": {TARGET: 2},
    "chromeos-base/autotest-tests-bluetooth": {TARGET: 2},
    "chromeos-base/autotest-tests-cheets": {TARGET: 2},
    "chromeos-base/autotest-tests-cryptohome": {TARGET: 2},
    "chromeos-base/autotest-tests-debugd": {TARGET: 2},
    "chromeos-base/autotest-tests-graphics": {TARGET: 2},
    "chromeos-base/autotest-tests-ownershipapi": {TARGET: 2},
    "chromeos-base/autotest-tests-power": {TARGET: 2},
    "chromeos-base/autotest-tests-security": {TARGET: 2},
    "chromeos-base/autotest-tests-shill": {TARGET: 2},
    "chromeos-base/autotest-tests-toolchain": {TARGET: 2},
    "chromeos-base/autotest-tests-touchpad": {TARGET: 2},
    "chromeos-base/autotest-tests-tpm": {TARGET: 2},
    "chromeos-base/autotest-tests-vm-host": {TARGET: 2},
    "chromeos-base/avtest_label_detect": {TARGET: 2},
    "chromeos-base/biod": {TARGET: 32},
    "chromeos-base/biod_proxy": {TARGET: 4},
    "chromeos-base/bootcomplete-login": {TARGET: 2},
    "chromeos-base/bootid-logger": {TARGET: 8},
    "chromeos-base/bootlockbox": {TARGET: 8},
    "chromeos-base/bootlockbox-client": {TARGET: 2},
    "chromeos-base/bootsplash": {TARGET: 4},
    "chromeos-base/bootstat": {TARGET: 2},
    "chromeos-base/borealis-dlc": {TARGET: 2},
    "chromeos-base/borealis-host-tools": {TARGET: 2},
    "chromeos-base/cbor": {TARGET: 4},
    "chromeos-base/cdm-oemcrypto": {TARGET: 16},
    "chromeos-base/cdm-oemcrypto-hw-test": {TARGET: 16},
    "chromeos-base/cdm-oemcrypto-hw-test-wv14": {TARGET: 16},
    "chromeos-base/cdm-oemcrypto-wv14": {TARGET: 8},
    "chromeos-base/chaps": {TARGET: 16},
    "chromeos-base/chaps-client": {TARGET: 4},
    "chromeos-base/chrome-binary-tests": {TARGET: 2},
    "chromeos-base/chrome-icu": {TARGET: 2},
    "chromeos-base/chromeos-activate-date": {TARGET: 2},
    "chromeos-base/chromeos-assets": {TARGET: 2},
    "chromeos-base/chromeos-auth-config": {TARGET: 2},
    "chromeos-base/chromeos-base": {HOST: 2, TARGET: 2},
    "chromeos-base/chromeos-board-default-apps-brya": {TARGET: 2},
    "chromeos-base/chromeos-board-default-arc-apps-brya": {TARGET: 2},
    "chromeos-base/chromeos-bsp-baseboard-brya": {TARGET: 2},
    "chromeos-base/chromeos-bsp-brya": {TARGET: 2},
    "chromeos-base/chromeos-bsp-brya-private": {TARGET: 8},
    "chromeos-base/chromeos-bsp-test-brya-private": {TARGET: 2},
    "chromeos-base/chromeos-ca-certificates": {TARGET: 2},
    "chromeos-base/chromeos-cheets": {TARGET: 2},
    "chromeos-base/chromeos-common-script": {TARGET: 2},
    "chromeos-base/chromeos-config": {TARGET: 2},
    "chromeos-base/chromeos-config-bsp": {TARGET: 2},
    "chromeos-base/chromeos-config-bsp-private": {TARGET: 2},
    "chromeos-base/chromeos-config-host": {HOST: 2},
    "chromeos-base/chromeos-config-tools": {TARGET: 4},
    "chromeos-base/chromeos-cr50": {TARGET: 2},
    "chromeos-base/chromeos-cr50-dev": {TARGET: 2},
    "chromeos-base/chromeos-cr50-scripts": {TARGET: 2},
    "chromeos-base/chromeos-dbus-bindings": {HOST: 4, TARGET: 4},
    "chromeos-base/chromeos-default-apps": {TARGET: 2},
    "chromeos-base/chromeos-default-arc-apps": {TARGET: 2},
    "chromeos-base/chromeos-dev-root": {TARGET: 2},
    "chromeos-base/chromeos-ec": {TARGET: 32},
    "chromeos-base/chromeos-ec-headers": {TARGET: 2},
    "chromeos-base/chromeos-ec-private-files": {TARGET: 2},
    "chromeos-base/chromeos-ec-private-files-null": {TARGET: 2},
    "chromeos-base/chromeos-firewall-init": {TARGET: 2},
    "chromeos-base/chromeos-firmware-brya": {TARGET: 2},
    "chromeos-base/chromeos-firmware-fpmcu": {TARGET: 2},
    "chromeos-base/chromeos-firmware-null": {TARGET: 2},
    "chromeos-base/chromeos-fonts": {TARGET: 2},
    "chromeos-base/chromeos-fpmcu-bloonchipper-unittests": {TARGET: 32},
    "chromeos-base/chromeos-fpmcu-dartmonkey-unittests": {TARGET: 32},
    "chromeos-base/chromeos-fpmcu-helipilot-unittests": {TARGET: 32},
    "chromeos-base/chromeos-fpmcu-test": {TARGET: 4},
    "chromeos-base/chromeos-gce-l1-vkms": {TARGET: 2},
    "chromeos-base/chromeos-gsc-dev": {TARGET: 2},
    "chromeos-base/chromeos-imageburner": {TARGET: 2},
    "chromeos-base/chromeos-init": {TARGET: 16},
    "chromeos-base/chromeos-installer": {TARGET: 8},
    "chromeos-base/chromeos-installshim": {TARGET: 2},
    "chromeos-base/chromeos-lacros": {TARGET: 2},
    "chromeos-base/chromeos-login": {TARGET: 8},
    "chromeos-base/chromeos-machine-id-regen": {TARGET: 4},
    "chromeos-base/chromeos-osrelease": {TARGET: 2},
    "chromeos-base/chromeos-pita": {TARGET: 4},
    "chromeos-base/chromeos-ssh-testkeys": {TARGET: 2},
    "chromeos-base/chromeos-sshd-init": {TARGET: 2},
    "chromeos-base/chromeos-storage-info": {TARGET: 2},
    "chromeos-base/chromeos-test-init": {TARGET: 2},
    "chromeos-base/chromeos-test-root": {TARGET: 2},
    "chromeos-base/chromeos-test-testauthkeys": {TARGET: 2},
    "chromeos-base/chromeos-touch-common": {TARGET: 4},
    "chromeos-base/chromeos-touch-etphidiap": {TARGET: 2},
    "chromeos-base/chromeos-trim": {TARGET: 2},
    "chromeos-base/chromiumos-assets": {TARGET: 2},
    "chromeos-base/chunnel": {TARGET: 8},
    "chromeos-base/common-assets": {TARGET: 2},
    "chromeos-base/crash-reporter": {TARGET: 8},
    "chromeos-base/cros-camera": {TARGET: 4},
    "chromeos-base/cros-camera-android-deps": {TARGET: 2},
    "chromeos-base/cros-camera-libs": {TARGET: 16},
    "chromeos-base/cros-camera-tool": {TARGET: 2},
    "chromeos-base/cros-config-api": {HOST: 2, TARGET: 2},
    "chromeos-base/cros-disks": {TARGET: 16},
    "chromeos-base/crosdns": {TARGET: 4},
    "chromeos-base/crosh": {TARGET: 16},
    "chromeos-base/crosh-extension": {TARGET: 2},
    "chromeos-base/crosid": {TARGET: 2},
    "chromeos-base/crosier-chrome": {TARGET: 2},
    "chromeos-base/croslog": {TARGET: 16},
    "chromeos-base/crostini_client": {TARGET: 2},
    "chromeos-base/crosvm": {TARGET: 8},
    "chromeos-base/cryptohome": {TARGET: 32},
    "chromeos-base/cryptohome-client": {TARGET: 2},
    "chromeos-base/cryptohome-dev-utils": {TARGET: 32},
    "chromeos-base/debugd": {TARGET: 8},
    "chromeos-base/debugd-client": {TARGET: 2},
    "chromeos-base/demo_mode_resources": {TARGET: 2},
    "chromeos-base/dev-install": {TARGET: 2},
    "chromeos-base/device_management": {TARGET: 8},
    "chromeos-base/device_management-client": {TARGET: 4},
    "chromeos-base/diagnostics": {TARGET: 16},
    "chromeos-base/diagnostics-minidiag": {TARGET: 4},
    "chromeos-base/discod": {TARGET: 8},
    "chromeos-base/dlcservice": {TARGET: 8},
    "chromeos-base/dlcservice-client": {TARGET: 2},
    "chromeos-base/dlcservice-metadata": {TARGET: 2},
    "chromeos-base/dlp": {TARGET: 8},
    "chromeos-base/dns-proxy": {TARGET: 4},
    "chromeos-base/drivefs": {TARGET: 2},
    "chromeos-base/drm-tests": {TARGET: 2},
    "chromeos-base/easy-unlock": {TARGET: 4},
    "chromeos-base/easy-unlock-crypto": {TARGET: 4},
    "chromeos-base/ec-devutils": {TARGET: 2},
    "chromeos-base/ec-utils": {TARGET: 2},
    "chromeos-base/ec-utils-test": {TARGET: 2},
    "chromeos-base/edk2-ovmf-dlc": {TARGET: 2},
    "chromeos-base/elan_i2chid_tools": {TARGET: 2},
    "chromeos-base/epstps2iap": {TARGET: 4},
    "chromeos-base/factory": {TARGET: 4},
    "chromeos-base/factory-baseboard": {TARGET: 2},
    "chromeos-base/factory-board": {TARGET: 2},
    "chromeos-base/factory-mini": {TARGET: 2},
    "chromeos-base/factory_fai": {TARGET: 8},
    "chromeos-base/factory_generate_ssfc": {TARGET: 8},
    "chromeos-base/factory_installer": {TARGET: 32},
    "chromeos-base/factory_installer_rust": {TARGET: 8},
    "chromeos-base/factory_runtime_probe": {TARGET: 32},
    "chromeos-base/factory_ufs": {TARGET: 4},
    "chromeos-base/fbpreprocessord": {TARGET: 4},
    "chromeos-base/feature-management-bsp": {TARGET: 2},
    "chromeos-base/feature-management-data": {TARGET: 2},
    "chromeos-base/feature-management-private": {TARGET: 2},
    "chromeos-base/featured": {TARGET: 8},
    "chromeos-base/federated-service": {TARGET: 8},
    "chromeos-base/fibocom-firmware": {TARGET: 8},
    "chromeos-base/fio-dlc": {TARGET: 2},
    "chromeos-base/flex_bluetooth": {TARGET: 4},
    "chromeos-base/foomatic_shell": {TARGET: 4},
    "chromeos-base/fusebox": {TARGET: 2},
    "chromeos-base/g2f_tools": {TARGET: 2},
    "chromeos-base/g2update_tool": {TARGET: 2},
    "chromeos-base/gdix_hid_firmware_update": {TARGET: 2},
    "chromeos-base/gemalto-firmware": {TARGET: 4},
    "chromeos-base/gestures": {TARGET: 16},
    "chromeos-base/gestures-conf": {TARGET: 2},
    "chromeos-base/glbench": {TARGET: 2},
    "chromeos-base/glib-bridge": {TARGET: 4},
    "chromeos-base/goldctl": {TARGET: 2},
    "chromeos-base/google-breakpad": {HOST: 16, TARGET: 8},
    "chromeos-base/google-lpa": {TARGET: 8},
    "chromeos-base/google-sans-fonts": {TARGET: 2},
    "chromeos-base/graphics-expectations": {TARGET: 2},
    "chromeos-base/graphics-private": {TARGET: 2},
    "chromeos-base/graphics-utils": {TARGET: 2},
    "chromeos-base/graphics-utils-go": {TARGET: 4},
    "chromeos-base/graphics-utils-python": {TARGET: 2},
    "chromeos-base/hardware_verifier": {TARGET: 8},
    "chromeos-base/hardware_verifier_proto": {TARGET: 4},
    "chromeos-base/heartd": {TARGET: 4},
    "chromeos-base/heartd-tool": {TARGET: 2},
    "chromeos-base/hermes": {TARGET: 8},
    "chromeos-base/houdini-tm": {TARGET: 2},
    "chromeos-base/hps-firmware-images": {TARGET: 2},
    "chromeos-base/hps-tool": {TARGET: 8},
    "chromeos-base/hpsd": {TARGET: 8},
    "chromeos-base/hwsec-test-utils": {TARGET: 8},
    "chromeos-base/hwsec-utils": {TARGET: 4},
    "chromeos-base/iioservice": {TARGET: 8},
    "chromeos-base/iioservice_simpleclient": {TARGET: 16},
    "chromeos-base/imageloader": {TARGET: 8},
    "chromeos-base/imageloader-client": {TARGET: 2},
    "chromeos-base/inputcontrol": {TARGET: 2},
    "chromeos-base/ippusb_bridge": {TARGET: 4},
    "chromeos-base/kbmcu-firmware": {TARGET: 2},
    "chromeos-base/kerberos": {TARGET: 4},
    "chromeos-base/lexmark-fax-pnh": {TARGET: 2},
    "chromeos-base/libarc-attestation": {TARGET: 4},
    "chromeos-base/libbrillo": {TARGET: 16},
    "chromeos-base/libchrome": {HOST: 32, TARGET: 32},
    "chromeos-base/libchromeos-ui": {TARGET: 2},
    "chromeos-base/libchromeos-use-flags": {TARGET: 2},
    "chromeos-base/libcontainer": {TARGET: 2},
    "chromeos-base/libcrossystem": {TARGET: 2},
    "chromeos-base/libec": {TARGET: 16},
    "chromeos-base/libevdev": {TARGET: 2},
    "chromeos-base/libhwsec": {TARGET: 32},
    "chromeos-base/libhwsec-foundation": {TARGET: 8},
    "chromeos-base/libiioservice_ipc": {TARGET: 4},
    "chromeos-base/libipp": {TARGET: 2},
    "chromeos-base/libmems": {TARGET: 4},
    "chromeos-base/libpasswordprovider": {TARGET: 2},
    "chromeos-base/libsar": {TARGET: 2},
    "chromeos-base/libsegmentation": {TARGET: 8},
    "chromeos-base/libsegmentation-test": {TARGET: 2},
    "chromeos-base/libstorage": {TARGET: 4},
    "chromeos-base/libvda": {TARGET: 16},
    "chromeos-base/libvda-gpu-tests": {TARGET: 16},
    "chromeos-base/lorgnette": {TARGET: 16},
    "chromeos-base/lorgnette-client": {TARGET: 2},
    "chromeos-base/lorgnette-wwcb-tests": {TARGET: 4},
    "chromeos-base/lorgnette_cli": {TARGET: 16},
    "chromeos-base/lvmd": {TARGET: 2},
    "chromeos-base/lvmd-client": {TARGET: 2},
    "chromeos-base/mctk": {TARGET: 4},
    "chromeos-base/memd": {TARGET: 8},
    "chromeos-base/mems_setup": {TARGET: 4},
    "chromeos-base/metrics": {TARGET: 16},
    "chromeos-base/midis": {TARGET: 4},
    "chromeos-base/minijail": {HOST: 2, TARGET: 2},
    "chromeos-base/minios": {TARGET: 16},
    "chromeos-base/missive": {TARGET: 16},
    "chromeos-base/mist": {TARGET: 4},
    "chromeos-base/mitmproxy": {TARGET: 2},
    "chromeos-base/ml": {TARGET: 8},
    "chromeos-base/ml-benchmark": {TARGET: 16},
    "chromeos-base/ml-benchmark-drivers": {TARGET: 4},
    "chromeos-base/ml-client": {TARGET: 2},
    "chromeos-base/ml-cmdline": {TARGET: 16},
    "chromeos-base/ml-core-internal": {TARGET: 2},
    "chromeos-base/mock-biod-test-deps": {TARGET: 2},
    "chromeos-base/modem-diagnostics": {TARGET: 2},
    "chromeos-base/modem-fw-dlc-anahera-l850": {TARGET: 2},
    "chromeos-base/modem-fw-dlc-brya-fm350": {TARGET: 2},
    "chromeos-base/modem-fw-dlc-brya-l850": {TARGET: 2},
    "chromeos-base/modem-fw-dlc-bryati50-fm350": {TARGET: 2},
    "chromeos-base/modem-fw-dlc-crota-fm101": {TARGET: 2},
    "chromeos-base/modem-fw-dlc-primus-l850": {TARGET: 4},
    "chromeos-base/modem-fw-dlc-redrix-fm350": {TARGET: 2},
    "chromeos-base/modem-fw-dlc-redrix-l850": {TARGET: 2},
    "chromeos-base/modem-fw-dlc-vell-fm350": {TARGET: 2},
    "chromeos-base/modem-utilities": {TARGET: 2},
    "chromeos-base/modemfwd": {TARGET: 8},
    "chromeos-base/modemfwd-helpers": {TARGET: 2},
    "chromeos-base/modemfwd-proto": {TARGET: 2},
    "chromeos-base/modemloggerd": {TARGET: 4},
    "chromeos-base/modemloggerd-dev": {TARGET: 4},
    "chromeos-base/mojo_service_manager": {TARGET: 4},
    "chromeos-base/mojo_service_manager-test": {TARGET: 2},
    "chromeos-base/monotype-fonts": {TARGET: 2},
    "chromeos-base/mount-passthrough": {TARGET: 4},
    "chromeos-base/mtpd": {TARGET: 4},
    "chromeos-base/mttools": {TARGET: 2},
    "chromeos-base/net-base": {TARGET: 8},
    "chromeos-base/node_exporter": {TARGET: 2},
    "chromeos-base/nsswitch": {TARGET: 2},
    "chromeos-base/oobe_config": {TARGET: 8},
    "chromeos-base/openssh-server-init": {TARGET: 2},
    "chromeos-base/p2p": {TARGET: 8},
    "chromeos-base/patchpanel": {TARGET: 8},
    "chromeos-base/patchpanel-client": {TARGET: 2},
    "chromeos-base/pciguard": {TARGET: 4},
    "chromeos-base/pdfc-scripts": {TARGET: 2},
    "chromeos-base/percetto": {TARGET: 2},
    "chromeos-base/perfetto": {HOST: 16, TARGET: 8},
    "chromeos-base/perfetto_simple_producer": {TARGET: 2},
    "chromeos-base/permission_broker": {TARGET: 8},
    "chromeos-base/permission_broker-client": {TARGET: 2},
    "chromeos-base/pinweaver": {TARGET: 2},
    "chromeos-base/pixart_tpfwup": {TARGET: 2},
    "chromeos-base/policy-go-proto": {TARGET: 2},
    "chromeos-base/policy_utils": {TARGET: 2},
    "chromeos-base/power_manager": {TARGET: 16},
    "chromeos-base/power_manager-client": {TARGET: 2},
    "chromeos-base/pp_cli": {TARGET: 2},
    "chromeos-base/prebuilt-sample-dlc": {TARGET: 2},
    "chromeos-base/prebuilt-test-dlc": {TARGET: 2},
    "chromeos-base/print_tools": {TARGET: 4},
    "chromeos-base/printscanmgr": {TARGET: 4},
    "chromeos-base/private_computing": {TARGET: 2},
    "chromeos-base/protofiles": {TARGET: 2},
    "chromeos-base/pw_tokenizer": {TARGET: 2},
    "chromeos-base/pywalt": {TARGET: 2},
    "chromeos-base/quipper": {TARGET: 8},
    "chromeos-base/racc-config-brya": {TARGET: 2},
    "chromeos-base/recover-duts": {TARGET: 2},
    "chromeos-base/redaction_tool": {TARGET: 4},
    "chromeos-base/regions": {TARGET: 2},
    "chromeos-base/regions-private": {TARGET: 2},
    "chromeos-base/reporting-proto": {TARGET: 2},
    "chromeos-base/resourced": {TARGET: 8},
    "chromeos-base/rgbkbd": {TARGET: 4},
    "chromeos-base/rmad": {TARGET: 32},
    "chromeos-base/rmad-config-brya": {TARGET: 2},
    "chromeos-base/rmi4utils": {TARGET: 2},
    "chromeos-base/routing-simulator": {TARGET: 4},
    "chromeos-base/run_oci": {TARGET: 4},
    "chromeos-base/runtime_probe": {TARGET: 16},
    "chromeos-base/runtime_probe-client": {TARGET: 2},
    "chromeos-base/sample-dlc": {TARGET: 2},
    "chromeos-base/sane-backends-test": {TARGET: 2},  # nocheck
    "chromeos-base/scaled-dlc": {TARGET: 2},
    "chromeos-base/screen-capture-utils": {TARGET: 4},
    "chromeos-base/secagentd": {TARGET: 8},
    "chromeos-base/secanomalyd": {TARGET: 4},
    "chromeos-base/secure-erase-file": {TARGET: 4},
    "chromeos-base/secure-wipe": {TARGET: 2},
    "chromeos-base/selinux-policy": {TARGET: 2},
    "chromeos-base/session_manager-client": {TARGET: 2},
    "chromeos-base/shadercached": {TARGET: 8},
    "chromeos-base/shill": {TARGET: 32},
    "chromeos-base/shill-client": {TARGET: 2},
    "chromeos-base/shill-dbus-client": {TARGET: 2},
    "chromeos-base/shill-test-scripts": {TARGET: 2},
    "chromeos-base/smbfs": {TARGET: 8},
    "chromeos-base/smbprovider": {TARGET: 8},
    "chromeos-base/sof-binary": {TARGET: 2},
    "chromeos-base/sof-dts-bundle": {TARGET: 2},
    "chromeos-base/sof-rtnr-bundle": {TARGET: 2},
    "chromeos-base/sof-topology": {TARGET: 2},
    "chromeos-base/sof-waves-bundle": {TARGET: 2},
    "chromeos-base/spaced": {TARGET: 4},
    "chromeos-base/swap_management": {TARGET: 8},
    "chromeos-base/syslog-cat": {TARGET: 2},
    "chromeos-base/system-locales": {TARGET: 2},
    "chromeos-base/system-proxy": {TARGET: 4},
    "chromeos-base/system_api": {TARGET: 8},
    "chromeos-base/tast-build-deps": {TARGET: 2},
    "chromeos-base/tast-local-apks-cros": {TARGET: 32},
    "chromeos-base/tast-local-helpers-cros": {TARGET: 2},
    "chromeos-base/tast-local-test-runner": {TARGET: 2},
    "chromeos-base/tast-local-tests": {TARGET: 2},
    "chromeos-base/tast-local-tests-cros": {TARGET: 8},
    "chromeos-base/tast-local-tests-crosint": {TARGET: 4},
    "chromeos-base/tast-local-tests-crosint_intel": {TARGET: 4},
    "chromeos-base/tast-remote-tests": {TARGET: 2},
    "chromeos-base/tast-remote-tests-cros": {TARGET: 16},
    "chromeos-base/tast-remote-tests-crosint": {TARGET: 4},
    "chromeos-base/tast-remote-tests-crosint_intel": {TARGET: 4},
    "chromeos-base/tast-tests-intel-local-data": {TARGET: 2},
    "chromeos-base/tast-tests-local-data": {TARGET: 2},
    "chromeos-base/tast-tests-private-local-data": {TARGET: 2},
    "chromeos-base/tast-tests-remote-data": {TARGET: 2},
    "chromeos-base/tast-use-flags": {TARGET: 2},
    "chromeos-base/telemetry": {TARGET: 2},
    "chromeos-base/termina-dlc": {TARGET: 2},
    "chromeos-base/termina-tools-dlc": {TARGET: 2},
    "chromeos-base/test-dlc": {TARGET: 2},
    "chromeos-base/timberslide": {TARGET: 4},
    "chromeos-base/timeofday-dlc": {TARGET: 2},
    "chromeos-base/toolchain-tests": {TARGET: 2},
    "chromeos-base/touch_firmware_test": {TARGET: 2},
    "chromeos-base/touch_updater": {TARGET: 2},
    "chromeos-base/tpm2": {TARGET: 2},
    "chromeos-base/tpm2-simulator": {TARGET: 8},
    "chromeos-base/tpm_manager": {TARGET: 8},
    "chromeos-base/tpm_manager-client": {TARGET: 2},
    "chromeos-base/tpm_softclear_utils": {TARGET: 4},
    "chromeos-base/trunks": {TARGET: 8},
    "chromeos-base/tty": {TARGET: 2},
    "chromeos-base/typecd": {TARGET: 16},
    "chromeos-base/u-boot-license": {TARGET: 2},
    "chromeos-base/u-boot-scripts": {TARGET: 4},
    "chromeos-base/u2fd": {TARGET: 8},
    "chromeos-base/u2fd-client": {TARGET: 4},
    "chromeos-base/u2fd-corp": {TARGET: 4},
    "chromeos-base/update-policy-chromeos": {TARGET: 2},
    "chromeos-base/update-utils": {TARGET: 2},
    "chromeos-base/update_engine": {TARGET: 32},
    "chromeos-base/update_engine-client": {TARGET: 2},
    "chromeos-base/usb_bouncer": {TARGET: 2},
    "chromeos-base/userfeedback": {TARGET: 2},
    "chromeos-base/usi-test": {TARGET: 2},
    "chromeos-base/vboot_reference": {HOST: 4, TARGET: 2},
    "chromeos-base/vboot_reference-tests": {TARGET: 2},
    "chromeos-base/verity": {TARGET: 4},
    "chromeos-base/virtual-file-provider": {TARGET: 4},
    "chromeos-base/virtual-usb-printer": {TARGET: 16},
    "chromeos-base/vkbench": {TARGET: 2},
    "chromeos-base/vm_host_tools": {TARGET: 16},
    "chromeos-base/vm_protos": {TARGET: 4},
    "chromeos-base/vpd": {TARGET: 4},
    "chromeos-base/vtpm": {TARGET: 8},
    "chromeos-base/wprgo": {TARGET: 2},
    "chromeos-base/xdr-proto": {TARGET: 2},
    "chromeos-base/zephyr-build-tools": {HOST: 16},
    "chromeos-borealis/borealis-shader-cache-1222670-dlc-axe-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-1222670-dlc-batrider-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-1222670-dlc-clinkz-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-1222670-dlc-dazzle-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-1222670-dlc-enigma-id-brya": {TARGET: 4},
    "chromeos-borealis/borealis-shader-cache-1222670-dlc-grimstroke-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-290730-dlc-axe-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-290730-dlc-batrider-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-290730-dlc-clinkz-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-290730-dlc-dazzle-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-290730-dlc-enigma-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-290730-dlc-grimstroke-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-375950-dlc-axe-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-375950-dlc-batrider-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-375950-dlc-clinkz-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-375950-dlc-dazzle-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-375950-dlc-enigma-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-375950-dlc-grimstroke-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-440-dlc-axe-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-440-dlc-batrider-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-440-dlc-clinkz-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-440-dlc-dazzle-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-440-dlc-enigma-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-440-dlc-grimstroke-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-570-dlc-axe-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-570-dlc-batrider-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-570-dlc-clinkz-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-570-dlc-dazzle-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-570-dlc-enigma-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-570-dlc-grimstroke-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-730-dlc-axe-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-730-dlc-batrider-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-730-dlc-clinkz-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-730-dlc-dazzle-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-730-dlc-enigma-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-730-dlc-grimstroke-id-brya": {TARGET: 2},
    "chromeos-borealis/borealis-shader-cache-brya": {TARGET: 2},
    "chromeos-languagepacks/extrafonts-ja": {TARGET: 2},
    "chromeos-languagepacks/extrafonts-ko": {TARGET: 2},
    "chromeos-languagepacks/handwriting-am": {TARGET: 2},
    "chromeos-languagepacks/handwriting-ar": {TARGET: 2},
    "chromeos-languagepacks/handwriting-base": {TARGET: 2},
    "chromeos-languagepacks/handwriting-be": {TARGET: 2},
    "chromeos-languagepacks/handwriting-bg": {TARGET: 2},
    "chromeos-languagepacks/handwriting-bn": {TARGET: 2},
    "chromeos-languagepacks/handwriting-ca": {TARGET: 2},
    "chromeos-languagepacks/handwriting-cs": {TARGET: 2},
    "chromeos-languagepacks/handwriting-da": {TARGET: 2},
    "chromeos-languagepacks/handwriting-de": {TARGET: 2},
    "chromeos-languagepacks/handwriting-el": {TARGET: 2},
    "chromeos-languagepacks/handwriting-es": {TARGET: 2},
    "chromeos-languagepacks/handwriting-et": {TARGET: 2},
    "chromeos-languagepacks/handwriting-fa": {TARGET: 4},
    "chromeos-languagepacks/handwriting-fi": {TARGET: 2},
    "chromeos-languagepacks/handwriting-fil": {TARGET: 2},
    "chromeos-languagepacks/handwriting-fr": {TARGET: 2},
    "chromeos-languagepacks/handwriting-ga": {TARGET: 2},
    "chromeos-languagepacks/handwriting-gu": {TARGET: 2},
    "chromeos-languagepacks/handwriting-hi": {TARGET: 2},
    "chromeos-languagepacks/handwriting-hr": {TARGET: 2},
    "chromeos-languagepacks/handwriting-hu": {TARGET: 2},
    "chromeos-languagepacks/handwriting-hy": {TARGET: 2},
    "chromeos-languagepacks/handwriting-id": {TARGET: 2},
    "chromeos-languagepacks/handwriting-is": {TARGET: 2},
    "chromeos-languagepacks/handwriting-it": {TARGET: 2},
    "chromeos-languagepacks/handwriting-iw": {TARGET: 2},
    "chromeos-languagepacks/handwriting-ja": {TARGET: 2},
    "chromeos-languagepacks/handwriting-ka": {TARGET: 2},
    "chromeos-languagepacks/handwriting-kk": {TARGET: 2},
    "chromeos-languagepacks/handwriting-km": {TARGET: 2},
    "chromeos-languagepacks/handwriting-kn": {TARGET: 2},
    "chromeos-languagepacks/handwriting-ko": {TARGET: 2},
    "chromeos-languagepacks/handwriting-lo": {TARGET: 2},
    "chromeos-languagepacks/handwriting-lt": {TARGET: 2},
    "chromeos-languagepacks/handwriting-lv": {TARGET: 4},
    "chromeos-languagepacks/handwriting-ml": {TARGET: 2},
    "chromeos-languagepacks/handwriting-mn": {TARGET: 2},
    "chromeos-languagepacks/handwriting-mr": {TARGET: 2},
    "chromeos-languagepacks/handwriting-ms": {TARGET: 2},
    "chromeos-languagepacks/handwriting-mt": {TARGET: 2},
    "chromeos-languagepacks/handwriting-my": {TARGET: 2},
    "chromeos-languagepacks/handwriting-ne": {TARGET: 2},
    "chromeos-languagepacks/handwriting-nl": {TARGET: 2},
    "chromeos-languagepacks/handwriting-no": {TARGET: 2},
    "chromeos-languagepacks/handwriting-or": {TARGET: 2},
    "chromeos-languagepacks/handwriting-pa": {TARGET: 2},
    "chromeos-languagepacks/handwriting-pl": {TARGET: 2},
    "chromeos-languagepacks/handwriting-pt": {TARGET: 2},
    "chromeos-languagepacks/handwriting-ro": {TARGET: 2},
    "chromeos-languagepacks/handwriting-ru": {TARGET: 2},
    "chromeos-languagepacks/handwriting-si": {TARGET: 2},
    "chromeos-languagepacks/handwriting-sk": {TARGET: 2},
    "chromeos-languagepacks/handwriting-sl": {TARGET: 2},
    "chromeos-languagepacks/handwriting-sr": {TARGET: 2},
    "chromeos-languagepacks/handwriting-sv": {TARGET: 2},
    "chromeos-languagepacks/handwriting-ta": {TARGET: 2},
    "chromeos-languagepacks/handwriting-te": {TARGET: 2},
    "chromeos-languagepacks/handwriting-th": {TARGET: 2},
    "chromeos-languagepacks/handwriting-ti": {TARGET: 2},
    "chromeos-languagepacks/handwriting-tr": {TARGET: 2},
    "chromeos-languagepacks/handwriting-uk": {TARGET: 2},
    "chromeos-languagepacks/handwriting-ur": {TARGET: 2},
    "chromeos-languagepacks/handwriting-vi": {TARGET: 2},
    "chromeos-languagepacks/handwriting-zh": {TARGET: 2},
    "chromeos-languagepacks/handwriting-zh-HK": {TARGET: 2},
    "chromeos-languagepacks/tts-bn-bd-b": {TARGET: 2},
    "chromeos-languagepacks/tts-bn-bd-c": {TARGET: 2},
    "chromeos-languagepacks/tts-cs-cz-b": {TARGET: 2},
    "chromeos-languagepacks/tts-cs-cz-c": {TARGET: 2},
    "chromeos-languagepacks/tts-da-dk-b": {TARGET: 2},
    "chromeos-languagepacks/tts-da-dk-c": {TARGET: 2},
    "chromeos-languagepacks/tts-de-de-b": {TARGET: 2},
    "chromeos-languagepacks/tts-de-de-c": {TARGET: 2},
    "chromeos-languagepacks/tts-el-gr-b": {TARGET: 2},
    "chromeos-languagepacks/tts-el-gr-c": {TARGET: 2},
    "chromeos-languagepacks/tts-en-au-b": {TARGET: 2},
    "chromeos-languagepacks/tts-en-au-c": {TARGET: 2},
    "chromeos-languagepacks/tts-en-gb-b": {TARGET: 2},
    "chromeos-languagepacks/tts-en-gb-c": {TARGET: 2},
    "chromeos-languagepacks/tts-en-us-b": {TARGET: 2},
    "chromeos-languagepacks/tts-en-us-c": {TARGET: 2},
    "chromeos-languagepacks/tts-es-es-b": {TARGET: 2},
    "chromeos-languagepacks/tts-es-es-c": {TARGET: 2},
    "chromeos-languagepacks/tts-es-us-b": {TARGET: 2},
    "chromeos-languagepacks/tts-es-us-c": {TARGET: 2},
    "chromeos-languagepacks/tts-fi-fi-b": {TARGET: 2},
    "chromeos-languagepacks/tts-fi-fi-c": {TARGET: 2},
    "chromeos-languagepacks/tts-fil-ph-b": {TARGET: 2},
    "chromeos-languagepacks/tts-fil-ph-c": {TARGET: 2},
    "chromeos-languagepacks/tts-fr-fr-b": {TARGET: 2},
    "chromeos-languagepacks/tts-fr-fr-c": {TARGET: 2},
    "chromeos-languagepacks/tts-hi-in-b": {TARGET: 2},
    "chromeos-languagepacks/tts-hi-in-c": {TARGET: 2},
    "chromeos-languagepacks/tts-hu-hu-b": {TARGET: 2},
    "chromeos-languagepacks/tts-hu-hu-c": {TARGET: 2},
    "chromeos-languagepacks/tts-id-id-b": {TARGET: 2},
    "chromeos-languagepacks/tts-id-id-c": {TARGET: 2},
    "chromeos-languagepacks/tts-it-it-b": {TARGET: 2},
    "chromeos-languagepacks/tts-it-it-c": {TARGET: 2},
    "chromeos-languagepacks/tts-ja-jp-b": {TARGET: 2},
    "chromeos-languagepacks/tts-ja-jp-c": {TARGET: 2},
    "chromeos-languagepacks/tts-km-kh-b": {TARGET: 2},
    "chromeos-languagepacks/tts-km-kh-c": {TARGET: 2},
    "chromeos-languagepacks/tts-ko-kr-b": {TARGET: 2},
    "chromeos-languagepacks/tts-ko-kr-c": {TARGET: 2},
    "chromeos-languagepacks/tts-nb-no-b": {TARGET: 2},
    "chromeos-languagepacks/tts-nb-no-c": {TARGET: 2},
    "chromeos-languagepacks/tts-ne-np-b": {TARGET: 2},
    "chromeos-languagepacks/tts-ne-np-c": {TARGET: 2},
    "chromeos-languagepacks/tts-nl-nl-b": {TARGET: 2},
    "chromeos-languagepacks/tts-nl-nl-c": {TARGET: 2},
    "chromeos-languagepacks/tts-pl-pl-b": {TARGET: 2},
    "chromeos-languagepacks/tts-pl-pl-c": {TARGET: 2},
    "chromeos-languagepacks/tts-pt-br-b": {TARGET: 2},
    "chromeos-languagepacks/tts-pt-br-c": {TARGET: 2},
    "chromeos-languagepacks/tts-pt-pt-b": {TARGET: 2},
    "chromeos-languagepacks/tts-pt-pt-c": {TARGET: 2},
    "chromeos-languagepacks/tts-si-lk-b": {TARGET: 2},
    "chromeos-languagepacks/tts-si-lk-c": {TARGET: 2},
    "chromeos-languagepacks/tts-sk-sk-b": {TARGET: 2},
    "chromeos-languagepacks/tts-sk-sk-c": {TARGET: 2},
    "chromeos-languagepacks/tts-sv-se-b": {TARGET: 2},
    "chromeos-languagepacks/tts-sv-se-c": {TARGET: 2},
    "chromeos-languagepacks/tts-th-th-b": {TARGET: 2},
    "chromeos-languagepacks/tts-th-th-c": {TARGET: 2},
    "chromeos-languagepacks/tts-tr-tr-b": {TARGET: 2},
    "chromeos-languagepacks/tts-tr-tr-c": {TARGET: 2},
    "chromeos-languagepacks/tts-uk-ua-b": {TARGET: 2},
    "chromeos-languagepacks/tts-uk-ua-c": {TARGET: 2},
    "chromeos-languagepacks/tts-vi-vn-b": {TARGET: 2},
    "chromeos-languagepacks/tts-vi-vn-c": {TARGET: 2},
    "chromeos-languagepacks/tts-yue-hk-b": {TARGET: 2},
    "chromeos-languagepacks/tts-yue-hk-c": {TARGET: 2},
    "chromeos-soda/libsoda": {TARGET: 2},
    "chromeos-soda/libsoda-model-de-at-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-de-be-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-de-ch-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-de-de-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-en-au-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-en-ca-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-en-gb-df23d1": {TARGET: 16},
    "chromeos-soda/libsoda-model-en-ie-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-en-in-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-en-sg-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-en-us": {TARGET: 2},
    "chromeos-soda/libsoda-model-en-us-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-es-us-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-fr-be-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-fr-ch-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-fr-fr-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-it-ch-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-it-it-df23d1": {TARGET: 2},
    "chromeos-soda/libsoda-model-ja-jp-df23d1": {TARGET: 2},
    "cross-armv7m-cros-eabi/binutils": {HOST: 8},
    "cross-armv7m-cros-eabi/compiler-rt": {HOST: 2},
    "cross-armv7m-cros-eabi/gcc": {HOST: 4},
    "cross-armv7m-cros-eabi/libcxx": {HOST: 4},
    "cross-armv7m-cros-eabi/llvm-libunwind": {HOST: 2},
    "cross-armv7m-cros-eabi/newlib": {HOST: 2},
    "cross-i686-cros-linux-gnu-bootstrap/gcc": {HOST: 16},
    "cross-i686-cros-linux-gnu/binutils": {HOST: 4},
    "cross-i686-cros-linux-gnu/glibc": {HOST: 8},
    "cross-i686-cros-linux-gnu/linux-headers": {HOST: 2},
    "cross-i686-cros-linux-gnu/llvm-libunwind": {HOST: 2},
    "cross-x86_64-cros-linux-gnu-bootstrap/gcc": {HOST: 8},
    "cross-x86_64-cros-linux-gnu/binutils": {HOST: 8},
    "cross-x86_64-cros-linux-gnu/gcc": {HOST: 8},
    "cross-x86_64-cros-linux-gnu/glibc": {HOST: 8},
    "cross-x86_64-cros-linux-gnu/go": {HOST: 4},
    "cross-x86_64-cros-linux-gnu/libcxx": {HOST: 4},
    "cross-x86_64-cros-linux-gnu/libxcrypt": {HOST: 2},
    "cross-x86_64-cros-linux-gnu/linux-headers": {HOST: 2},
    "cross-x86_64-cros-linux-gnu/llvm-libunwind": {HOST: 4},
    "cross-x86_64-cros-linux-gnu/rust": {HOST: 32},
    "dev-build/meson": {HOST: 2},
    "dev-cpp/abseil-cpp": {HOST: 16, TARGET: 16},
    "dev-cpp/benchmark": {TARGET: 2},
    "dev-cpp/eigen": {HOST: 2, TARGET: 2},
    "dev-cpp/gflags": {TARGET: 2},
    "dev-cpp/gtest": {HOST: 2, TARGET: 2},
    "dev-cpp/robin-hood-hashing": {TARGET: 2},
    "dev-db/lmdb": {TARGET: 2},
    "dev-db/sqlite": {HOST: 2, TARGET: 2},
    "dev-embedded/binman": {HOST: 2},
    "dev-embedded/coreboot-sdk": {HOST: 32},
    "dev-embedded/dfu-programmer": {TARGET: 2},
    "dev-embedded/dtoc": {HOST: 2},
    "dev-embedded/libftdi": {HOST: 2, TARGET: 2},
    "dev-embedded/u-boot-tools": {HOST: 2},
    "dev-go/afero": {HOST: 2, TARGET: 2},
    "dev-go/appengine": {HOST: 2, TARGET: 2},
    "dev-go/blackfriday": {TARGET: 2},
    "dev-go/boringssl-acvptool": {TARGET: 2},
    "dev-go/bufseekio": {TARGET: 2},
    "dev-go/cdp": {TARGET: 2},
    "dev-go/certificate-transparency-go": {TARGET: 2},
    "dev-go/check": {HOST: 2, TARGET: 4},
    "dev-go/cli": {TARGET: 2},
    "dev-go/clock": {TARGET: 2},
    "dev-go/cmp": {HOST: 2, TARGET: 2},
    "dev-go/cncf-xds": {HOST: 2, TARGET: 2},
    "dev-go/containerd": {TARGET: 2},
    "dev-go/crc8": {TARGET: 2},
    "dev-go/crypto": {HOST: 2, TARGET: 2},
    "dev-go/dbus": {TARGET: 2},
    "dev-go/delve": {TARGET: 2},
    "dev-go/demangle": {TARGET: 2},
    "dev-go/distribution": {TARGET: 2},
    "dev-go/dns": {TARGET: 2},
    "dev-go/docker": {TARGET: 2},
    "dev-go/dst": {TARGET: 2},
    "dev-go/enterprise-certificate-proxy": {HOST: 2, TARGET: 2},
    "dev-go/ep-gcp": {HOST: 2, TARGET: 2},
    "dev-go/ep-pvg": {HOST: 2, TARGET: 2},
    "dev-go/errcheck": {TARGET: 4},
    "dev-go/errors": {TARGET: 2},
    "dev-go/exif": {TARGET: 2},
    "dev-go/exp": {TARGET: 2},
    "dev-go/fogleman-gg": {TARGET: 2},
    "dev-go/fscrypt": {TARGET: 2},
    "dev-go/fsnotify": {TARGET: 4},
    "dev-go/gapi": {HOST: 2, TARGET: 2},
    "dev-go/gax": {TARGET: 2},
    "dev-go/gcp-compute": {HOST: 2, TARGET: 2},
    "dev-go/gcp-compute-metadata": {HOST: 2, TARGET: 2},
    "dev-go/genproto": {HOST: 2, TARGET: 2},
    "dev-go/glog": {HOST: 2, TARGET: 2},
    "dev-go/go-arch": {TARGET: 2},
    "dev-go/go-attestation": {TARGET: 2},
    "dev-go/go-billy": {TARGET: 2},
    "dev-go/go-connections": {TARGET: 2},
    "dev-go/go-diff": {TARGET: 2},
    "dev-go/go-difflib": {HOST: 4, TARGET: 2},
    "dev-go/go-digest": {TARGET: 2},
    "dev-go/go-fonts-liberation": {TARGET: 2},
    "dev-go/go-image": {TARGET: 2},
    "dev-go/go-ini": {TARGET: 2},
    "dev-go/go-latex": {TARGET: 2},
    "dev-go/go-matroska": {TARGET: 2},
    "dev-go/go-md2man": {TARGET: 2},
    "dev-go/go-optional": {TARGET: 2},
    "dev-go/go-pdf": {TARGET: 2},
    "dev-go/go-serial": {TARGET: 2},
    "dev-go/go-spew": {HOST: 2, TARGET: 4},
    "dev-go/go-sys": {HOST: 2, TARGET: 2},
    "dev-go/go-sysconf": {TARGET: 2},
    "dev-go/go-tools": {HOST: 2, TARGET: 2},
    "dev-go/go-tpm": {TARGET: 2},
    "dev-go/go-tspi": {TARGET: 2},
    "dev-go/go-units": {TARGET: 2},
    "dev-go/go-webcam": {TARGET: 2},
    "dev-go/godebug": {TARGET: 2},
    "dev-go/gofpdf": {TARGET: 2},
    "dev-go/gofpdi": {TARGET: 2},
    "dev-go/gogo-protobuf": {TARGET: 2},
    "dev-go/golang-evdev": {TARGET: 2},
    "dev-go/golang-freetype": {TARGET: 2},
    "dev-go/golang-groupcache": {HOST: 4, TARGET: 2},
    "dev-go/goldmark": {HOST: 2, TARGET: 2},
    "dev-go/golint": {HOST: 4, TARGET: 2},
    "dev-go/gonum": {TARGET: 2},
    "dev-go/gonum-plot": {TARGET: 2},
    "dev-go/gopacket": {TARGET: 2},
    "dev-go/gopsutil": {TARGET: 2},
    "dev-go/goselect": {TARGET: 2},
    "dev-go/grpc": {HOST: 2, TARGET: 2},
    "dev-go/image-spec": {TARGET: 2},
    "dev-go/infra-proto": {TARGET: 2},
    "dev-go/jennifer": {TARGET: 2},
    "dev-go/kr-fs": {HOST: 2, TARGET: 2},
    "dev-go/kr-text": {HOST: 4, TARGET: 2},
    "dev-go/libcontainer": {TARGET: 2},
    "dev-go/logex": {TARGET: 2},
    "dev-go/logrus": {TARGET: 2},
    "dev-go/lucicfg": {HOST: 2},
    "dev-go/mdns": {TARGET: 2},
    "dev-go/misspell": {TARGET: 2},
    "dev-go/mock": {TARGET: 2},
    "dev-go/mod": {HOST: 2, TARGET: 2},
    "dev-go/mount": {TARGET: 2},
    "dev-go/mountinfo": {TARGET: 2},
    "dev-go/mp4": {TARGET: 2},
    "dev-go/net": {HOST: 2, TARGET: 2},
    "dev-go/numcpus": {TARGET: 2},
    "dev-go/oauth2": {HOST: 2, TARGET: 2},
    "dev-go/objx": {HOST: 2, TARGET: 2},
    "dev-go/opencensus": {TARGET: 2},
    "dev-go/perfetto-protos": {TARGET: 2},
    "dev-go/pprof": {TARGET: 2},
    "dev-go/pretty": {HOST: 2, TARGET: 2},
    "dev-go/protobuf": {HOST: 2, TARGET: 2},
    "dev-go/protobuf-legacy-api": {HOST: 4, TARGET: 2},
    "dev-go/pty": {HOST: 2, TARGET: 2},
    "dev-go/readline": {TARGET: 2},
    "dev-go/regexp2": {TARGET: 2},
    "dev-go/rsc-io-pdf": {TARGET: 2},
    "dev-go/selinux": {TARGET: 2},
    "dev-go/sftp": {HOST: 2, TARGET: 2},
    "dev-go/smetrics": {TARGET: 2},
    "dev-go/staticcheck": {TARGET: 4},
    "dev-go/strcase": {HOST: 4, TARGET: 2},
    "dev-go/subcommands": {TARGET: 2},
    "dev-go/svgo": {TARGET: 2},
    "dev-go/sync": {HOST: 2, TARGET: 2},
    "dev-go/syzkaller": {TARGET: 16},
    "dev-go/tail": {TARGET: 2},
    "dev-go/tarm-serial": {TARGET: 2},
    "dev-go/term": {HOST: 2, TARGET: 2},
    "dev-go/test": {TARGET: 2},
    "dev-go/testify": {HOST: 2, TARGET: 2},
    "dev-go/text": {HOST: 2, TARGET: 2},
    "dev-go/tomb": {TARGET: 2},
    "dev-go/toml": {TARGET: 2},
    "dev-go/uuid": {HOST: 2, TARGET: 2},
    "dev-go/vnc2video": {TARGET: 2},
    "dev-go/vsock": {TARGET: 2},
    "dev-go/websocket": {TARGET: 2},
    "dev-go/writeseeker": {TARGET: 2},
    "dev-go/xerrors": {HOST: 2, TARGET: 2},
    "dev-go/xxhash": {HOST: 4, TARGET: 2},
    "dev-go/yaml": {HOST: 2, TARGET: 2},
    "dev-java/icedtea-bin": {HOST: 2},
    "dev-java/java-config": {HOST: 4},
    "dev-java/openjdk-bin": {HOST: 2},
    "dev-lang/closure-compiler-bin": {HOST: 2},
    "dev-lang/go": {HOST: 4},
    "dev-lang/nasm": {HOST: 2},
    "dev-lang/perl": {HOST: 4},
    "dev-lang/python": {HOST: 2, TARGET: 2},
    "dev-lang/python-exec": {HOST: 2, TARGET: 2},
    "dev-lang/python-exec-conf": {HOST: 2, TARGET: 2},
    "dev-lang/rust-bootstrap": {HOST: 4},
    "dev-lang/rust-host": {HOST: 16},
    "dev-lang/swig": {HOST: 4},
    "dev-lang/tcl": {HOST: 4},
    "dev-lang/yasm": {HOST: 2},
    "dev-libs/boost": {TARGET: 8},
    "dev-libs/c-tap-harness": {TARGET: 2},
    "dev-libs/clhpp": {TARGET: 2},
    "dev-libs/closure-library": {HOST: 2},
    "dev-libs/confuse": {HOST: 2, TARGET: 2},
    "dev-libs/crc64c": {TARGET: 2},
    "dev-libs/double-conversion": {HOST: 2, TARGET: 2},
    "dev-libs/elfutils": {HOST: 4, TARGET: 4},
    "dev-libs/expat": {HOST: 2, TARGET: 2},
    "dev-libs/flatbuffers": {HOST: 16, TARGET: 2},
    "dev-libs/fribidi": {TARGET: 2},
    "dev-libs/glib": {HOST: 2, TARGET: 4},
    "dev-libs/gmp": {HOST: 2, TARGET: 4},
    "dev-libs/gobject-introspection": {HOST: 2, TARGET: 2},
    "dev-libs/gobject-introspection-common": {HOST: 4, TARGET: 2},
    "dev-libs/hidapi": {TARGET: 2},
    "dev-libs/json-c": {TARGET: 2},
    "dev-libs/json-glib": {TARGET: 4},
    "dev-libs/jsoncpp": {HOST: 2, TARGET: 2},
    "dev-libs/leveldb": {TARGET: 8},
    "dev-libs/libaio": {HOST: 4, TARGET: 2},
    "dev-libs/libassuan": {TARGET: 2},
    "dev-libs/libbpf": {TARGET: 4},
    "dev-libs/libbsd": {HOST: 2, TARGET: 2},
    "dev-libs/libclc": {HOST: 4},
    "dev-libs/libconfig": {TARGET: 2},
    "dev-libs/libcroco": {TARGET: 2},
    "dev-libs/libdaemon": {TARGET: 2},
    "dev-libs/libdivsufsort": {TARGET: 2},
    "dev-libs/libedit": {TARGET: 2},
    "dev-libs/libestr": {TARGET: 2},
    "dev-libs/libev": {HOST: 2, TARGET: 2},
    "dev-libs/libevdev": {TARGET: 2},
    "dev-libs/libevent": {HOST: 2, TARGET: 2},
    "dev-libs/libfastjson": {TARGET: 2},
    "dev-libs/libffi": {HOST: 2, TARGET: 2},
    "dev-libs/libfmt": {HOST: 2, TARGET: 2},
    "dev-libs/libgcrypt": {HOST: 2, TARGET: 2},
    "dev-libs/libgpg-error": {HOST: 2, TARGET: 2},
    "dev-libs/libgpiod": {TARGET: 2},
    "dev-libs/libgrammar": {TARGET: 2},
    "dev-libs/libgudev": {TARGET: 2},
    "dev-libs/libgusb": {TARGET: 2},
    "dev-libs/libhandwriting": {TARGET: 2},
    "dev-libs/libica": {TARGET: 2},
    "dev-libs/libjcat": {TARGET: 2},
    "dev-libs/libksba": {TARGET: 2},
    "dev-libs/libltdl": {HOST: 2, TARGET: 2},
    "dev-libs/libmspack": {HOST: 2},
    "dev-libs/libnl": {TARGET: 2},
    "dev-libs/libp11": {TARGET: 2},
    "dev-libs/libpcre": {TARGET: 2},
    "dev-libs/libpcre2": {HOST: 2, TARGET: 2},
    "dev-libs/libpthread-stubs": {TARGET: 2},
    "dev-libs/libsuggest": {TARGET: 2},
    "dev-libs/libtasn1": {HOST: 2, TARGET: 2},
    "dev-libs/libtextclassifier": {TARGET: 16},
    "dev-libs/libtraceevent": {TARGET: 2},
    "dev-libs/libtracefs": {TARGET: 4},
    "dev-libs/libunistring": {HOST: 2, TARGET: 2},
    "dev-libs/libusb": {HOST: 2, TARGET: 2},
    "dev-libs/libutf": {TARGET: 2},
    "dev-libs/libuv": {HOST: 2, TARGET: 2},
    "dev-libs/libverto": {HOST: 2, TARGET: 2},
    "dev-libs/libxml2": {HOST: 2, TARGET: 2},
    "dev-libs/libxmlb": {TARGET: 2},
    "dev-libs/libxslt": {HOST: 2, TARGET: 2},
    "dev-libs/libyaml": {HOST: 2, TARGET: 2},
    "dev-libs/libzip": {HOST: 2, TARGET: 2},
    "dev-libs/lzo": {HOST: 4, TARGET: 2},
    "dev-libs/marisa-aosp": {TARGET: 2},
    "dev-libs/ml-core": {TARGET: 4},
    "dev-libs/ml-core-tests": {TARGET: 4},
    "dev-libs/modp_b64": {HOST: 2, TARGET: 2},
    "dev-libs/mpc": {HOST: 2},
    "dev-libs/mpfr": {HOST: 4},
    "dev-libs/nettle": {HOST: 4, TARGET: 2},
    "dev-libs/npth": {TARGET: 2},
    "dev-libs/nspr": {HOST: 2, TARGET: 2},
    "dev-libs/nss": {HOST: 2, TARGET: 2},
    "dev-libs/nsync": {TARGET: 4},
    "dev-libs/oniguruma": {HOST: 2, TARGET: 2},
    "dev-libs/opencl-icd-loader": {TARGET: 2},
    "dev-libs/opencl-kernel-profiler": {TARGET: 2},
    "dev-libs/opensc": {TARGET: 4},
    "dev-libs/openssl": {HOST: 4, TARGET: 8},
    "dev-libs/pkcs11-helper": {TARGET: 2},
    "dev-libs/popt": {HOST: 4, TARGET: 2},
    "dev-libs/protobuf": {HOST: 32, TARGET: 16},
    "dev-libs/re2": {HOST: 4, TARGET: 8},
    "dev-libs/tinyxml2": {HOST: 2, TARGET: 2},
    "dev-libs/u_boot_pylib": {HOST: 2},
    "dev-libs/vala-common": {HOST: 4},
    "dev-libs/vulkan-shader-profiler": {TARGET: 2},
    "dev-libs/wayland": {TARGET: 2},
    "dev-libs/wayland-protocols": {TARGET: 2},
    "dev-libs/xmlrpc-c": {TARGET: 4},
    "dev-libs/xxhash": {HOST: 4, TARGET: 2},
    "dev-libs/xz-embedded": {TARGET: 2},
    "dev-perl/Devel-CheckLib": {HOST: 2},
    "dev-perl/Encode-Locale": {HOST: 2},
    "dev-perl/File-Listing": {HOST: 2},
    "dev-perl/HTML-Parser": {HOST: 2},
    "dev-perl/HTML-Tagset": {HOST: 2},
    "dev-perl/HTTP-Cookies": {HOST: 2},
    "dev-perl/HTTP-Date": {HOST: 2},
    "dev-perl/HTTP-Message": {HOST: 2},
    "dev-perl/HTTP-Negotiate": {HOST: 2},
    "dev-perl/IO-HTML": {HOST: 2},
    "dev-perl/LWP-MediaTypes": {HOST: 2},
    "dev-perl/Net-HTTP": {HOST: 2},
    "dev-perl/Parse-Yapp": {HOST: 2},
    "dev-perl/TimeDate": {HOST: 2},
    "dev-perl/Try-Tiny": {HOST: 2},
    "dev-perl/URI": {HOST: 2},
    "dev-perl/WWW-RobotRules": {HOST: 2},
    "dev-perl/XML-Parser": {HOST: 2},
    "dev-perl/libwww-perl": {HOST: 2},
    "dev-python/PySocks": {HOST: 2, TARGET: 2},
    "dev-python/atomicwrites": {HOST: 2},
    "dev-python/attrs": {HOST: 2, TARGET: 2},
    "dev-python/btsocket": {HOST: 2, TARGET: 2},
    "dev-python/certifi": {HOST: 4, TARGET: 2},
    "dev-python/cffi": {HOST: 2, TARGET: 2},
    "dev-python/chardet": {HOST: 2, TARGET: 2},
    "dev-python/cheroot": {TARGET: 2},
    "dev-python/cherrypy": {TARGET: 2},
    "dev-python/click": {TARGET: 2},
    "dev-python/colorama": {HOST: 2},
    "dev-python/contextlib2": {TARGET: 2},
    "dev-python/crcmod": {TARGET: 2},
    "dev-python/cryptography": {HOST: 2, TARGET: 2},
    "dev-python/cython": {HOST: 2, TARGET: 2},
    "dev-python/dbus-python": {HOST: 2, TARGET: 2},
    "dev-python/docopt": {HOST: 2},
    "dev-python/docutils": {HOST: 2},
    "dev-python/dpkt": {TARGET: 2},
    "dev-python/flatbuffers": {HOST: 2},
    "dev-python/greenlet": {TARGET: 2},
    "dev-python/grpcio": {HOST: 32, TARGET: 16},
    "dev-python/hid-tools": {TARGET: 2},
    "dev-python/httplib2": {TARGET: 2},
    "dev-python/hypothesis": {HOST: 2},
    "dev-python/idna": {HOST: 2, TARGET: 2},
    "dev-python/jaraco-functools": {TARGET: 2},
    "dev-python/jinja": {HOST: 2},
    "dev-python/jsonpointer": {HOST: 2, TARGET: 2},
    "dev-python/jsonrpclib": {HOST: 2, TARGET: 2},
    "dev-python/jsonschema": {HOST: 2, TARGET: 2},
    "dev-python/kconfiglib": {HOST: 2},
    "dev-python/lxml": {TARGET: 2},
    "dev-python/m2crypto": {HOST: 4},
    "dev-python/mako": {HOST: 2},
    "dev-python/markupsafe": {HOST: 2},
    "dev-python/mkvparse": {TARGET: 2},
    "dev-python/more-itertools": {HOST: 2, TARGET: 2},
    "dev-python/namespace-jaraco": {TARGET: 2},
    "dev-python/namespace-zope": {HOST: 4, TARGET: 2},
    "dev-python/netaddr": {TARGET: 2},
    "dev-python/netifaces": {TARGET: 2},
    "dev-python/numpy": {HOST: 2, TARGET: 2},
    "dev-python/olefile": {HOST: 2, TARGET: 2},
    "dev-python/packaging": {TARGET: 2},
    "dev-python/parse": {TARGET: 2},
    "dev-python/pexpect": {TARGET: 2},
    "dev-python/pillow": {HOST: 2, TARGET: 2},
    "dev-python/pluggy": {HOST: 2},
    "dev-python/ply": {HOST: 2, TARGET: 2},
    "dev-python/portend": {TARGET: 2},
    "dev-python/protobuf-python": {HOST: 2, TARGET: 2},
    "dev-python/psutil": {HOST: 2, TARGET: 2},
    "dev-python/ptyprocess": {TARGET: 2},
    "dev-python/py": {HOST: 2},
    "dev-python/pycparser": {HOST: 2, TARGET: 2},
    "dev-python/pycryptodome": {TARGET: 2},
    "dev-python/pydbus": {HOST: 2, TARGET: 2},
    "dev-python/pyelftools": {HOST: 2},
    "dev-python/pyftdi": {TARGET: 2},
    "dev-python/pygments": {HOST: 2},
    "dev-python/pygobject": {HOST: 2, TARGET: 2},
    "dev-python/pykwalify": {HOST: 2},
    "dev-python/pyopenssl": {HOST: 2, TARGET: 2},
    "dev-python/pyparsing": {TARGET: 2},
    "dev-python/pyrad": {TARGET: 2},
    "dev-python/pyrsistent": {HOST: 2, TARGET: 2},
    "dev-python/pyserial": {TARGET: 2},
    "dev-python/pytest": {HOST: 2},
    "dev-python/python-dateutil": {HOST: 2},
    "dev-python/python-evdev": {TARGET: 2},
    "dev-python/python-gnupg": {TARGET: 2},
    "dev-python/python-uinput": {TARGET: 2},
    "dev-python/pytz": {TARGET: 2},
    "dev-python/pyudev": {HOST: 2, TARGET: 2},
    "dev-python/pyusb": {TARGET: 2},
    "dev-python/pyxattr": {TARGET: 2},
    "dev-python/pyyaml": {HOST: 2, TARGET: 2},
    "dev-python/qrcode": {TARGET: 2},
    "dev-python/regex": {HOST: 2, TARGET: 2},
    "dev-python/requests": {HOST: 2, TARGET: 2},
    "dev-python/rfc3339-validator": {HOST: 2, TARGET: 2},
    "dev-python/rfc3986-validator": {HOST: 2, TARGET: 2},
    "dev-python/rfc3987": {HOST: 2, TARGET: 2},
    "dev-python/selenium": {TARGET: 2},
    "dev-python/setproctitle": {TARGET: 2},
    "dev-python/setuptools": {HOST: 4, TARGET: 2},
    "dev-python/setuptools_scm": {HOST: 2, TARGET: 2},
    "dev-python/six": {HOST: 2, TARGET: 2},
    "dev-python/sortedcontainers": {HOST: 2},
    "dev-python/strict-rfc3339": {HOST: 4, TARGET: 2},
    "dev-python/tempora": {TARGET: 2},
    "dev-python/testfixtures": {HOST: 2},
    "dev-python/urllib3": {HOST: 2, TARGET: 2},
    "dev-python/webcolors": {HOST: 2, TARGET: 2},
    "dev-python/websockify": {TARGET: 2},
    "dev-python/ws4py": {TARGET: 4},
    "dev-python/zc-lockfile": {TARGET: 2},
    "dev-python/zope-interface": {HOST: 2, TARGET: 2},
    "dev-rust/assertions": {TARGET: 2},
    "dev-rust/bindgen": {HOST: 8},
    "dev-rust/chromeos-dbus-bindings": {HOST: 2, TARGET: 2},
    "dev-rust/data_model": {TARGET: 2},
    "dev-rust/dbus-codegen": {HOST: 4},
    "dev-rust/featured": {TARGET: 2},
    "dev-rust/grpcio-compiler": {HOST: 2},
    "dev-rust/libchromeos": {TARGET: 8},
    "dev-rust/metrics_rs": {TARGET: 2},
    "dev-rust/minijail": {TARGET: 4},
    "dev-rust/minijail-sys": {TARGET: 2},
    "dev-rust/poll_token_derive": {TARGET: 2},
    "dev-rust/rustc-demangle-capi": {HOST: 2},
    "dev-rust/s9": {TARGET: 4},
    "dev-rust/system_api": {TARGET: 4},
    "dev-rust/third-party-crates-src": {HOST: 2, TARGET: 2},
    "dev-rust/tlsdate_dbus": {TARGET: 2},
    "dev-rust/vboot_reference-sys": {TARGET: 4},
    "dev-util/android-tools": {TARGET: 16},
    "dev-util/android-uiautomator-server": {TARGET: 4},
    "dev-util/apitrace": {TARGET: 4},
    "dev-util/b2": {HOST: 2},
    "dev-util/bazel": {HOST: 8},
    "dev-util/bpftool": {HOST: 2},
    "dev-util/bsdiff": {TARGET: 4},
    "dev-util/ccache": {HOST: 2},
    "dev-util/centralized-suites": {TARGET: 2},
    "dev-util/centralized-suites-private": {TARGET: 2},
    "dev-util/cmake": {HOST: 32},
    "dev-util/cmocka": {TARGET: 2},
    "dev-util/cros-test-ready": {TARGET: 2},
    "dev-util/cxxbridge-cmd": {HOST: 2},
    "dev-util/desktop-file-utils": {HOST: 2, TARGET: 2},
    "dev-util/gdbus-codegen": {HOST: 2},
    "dev-util/glib-utils": {HOST: 2, TARGET: 2},
    "dev-util/glslang": {HOST: 8, TARGET: 8},
    "dev-util/gn": {HOST: 4},
    "dev-util/gperf": {HOST: 2},
    "dev-util/gtk-doc-am": {HOST: 4, TARGET: 2},
    "dev-util/hdctools": {TARGET: 2},
    "dev-util/intel_clc": {HOST: 8},
    "dev-util/intltool": {HOST: 2, TARGET: 2},
    "dev-util/mem": {TARGET: 2},
    "dev-util/meson-format-array": {HOST: 2},
    "dev-util/ninja": {HOST: 2},
    "dev-util/opencl-headers": {TARGET: 2},
    "dev-util/pahole": {HOST: 2},
    "dev-util/patchutils": {HOST: 2},
    "dev-util/pdl-compiler": {HOST: 8},
    "dev-util/perf": {TARGET: 2},
    "dev-util/pkgconf": {HOST: 2},
    "dev-util/promu": {HOST: 4},
    "dev-util/puffin": {TARGET: 8},
    "dev-util/re2c": {HOST: 32},
    "dev-util/rt-tests": {TARGET: 2},
    "dev-util/scons": {HOST: 2},
    "dev-util/servo-config-dut-usb3-public": {TARGET: 2},
    "dev-util/shadowman": {HOST: 2},
    "dev-util/shflags": {TARGET: 2},
    "dev-util/socwatch-install": {TARGET: 2},
    "dev-util/spirv-headers": {HOST: 2, TARGET: 2},
    "dev-util/spirv-llvm": {HOST: 32},
    "dev-util/spirv-tools": {TARGET: 32},
    "dev-util/strace": {TARGET: 2},
    "dev-util/stressapptest": {TARGET: 2},
    "dev-util/trace-cmd": {TARGET: 2},
    "dev-util/turbostat": {TARGET: 2},
    "dev-util/u2f-ref-code": {TARGET: 2},
    "dev-util/volk": {TARGET: 2},
    "dev-util/vulkan-headers": {HOST: 2, TARGET: 2},
    "dev-util/vulkan-tools": {TARGET: 2},
    "dev-util/vulkan-utility-libraries": {TARGET: 2},
    "dev-util/wayland-scanner": {HOST: 2},
    "dev-vcs/git": {HOST: 8, TARGET: 4},
    "gnome-base/librsvg": {TARGET: 2},
    "media-fonts/croscorefonts": {TARGET: 2},
    "media-fonts/crosextrafonts": {TARGET: 2},
    "media-fonts/crosextrafonts-carlito": {TARGET: 2},
    "media-fonts/ipaex": {TARGET: 2},
    "media-fonts/ko-nanumfonts": {TARGET: 2},
    "media-fonts/lohitfonts-cros": {TARGET: 2},
    "media-fonts/morisawa-ud-fonts": {TARGET: 2},
    "media-fonts/noto-cjk": {TARGET: 2},
    "media-fonts/notofonts": {TARGET: 2},
    "media-fonts/robotofonts": {TARGET: 2},
    "media-fonts/tibt-jomolhari": {TARGET: 2},
    "media-gfx/deqp": {TARGET: 32},
    "media-gfx/deqp-runner": {TARGET: 8},
    "media-gfx/imagemagick": {TARGET: 2},
    "media-gfx/perceptualdiff": {TARGET: 2},
    "media-gfx/potrace": {TARGET: 2},
    "media-gfx/qrencode": {TARGET: 2},
    "media-gfx/sane-airscan": {TARGET: 2},  # nocheck
    "media-gfx/sane-backends": {TARGET: 2},  # nocheck
    "media-gfx/sane-backends-extras": {TARGET: 2},  # nocheck
    "media-gfx/sane-backends-pfu": {TARGET: 8},  # nocheck
    "media-gfx/vadumpcaps": {TARGET: 2},
    "media-gfx/zbar": {TARGET: 2},
    "media-libs/adl-aec-param": {TARGET: 2},
    "media-libs/adl-bandsplit-eq-param": {TARGET: 2},
    "media-libs/adl-cs35l41-dsm-param-brya": {TARGET: 2},
    "media-libs/adl-dsm-param": {TARGET: 2},
    "media-libs/adl-hotword-support": {TARGET: 2},
    "media-libs/adl-max98390-dsm-param-brya": {TARGET: 2},
    "media-libs/alsa-lib": {HOST: 2, TARGET: 2},
    "media-libs/alsa-ucm-conf": {TARGET: 2},
    "media-libs/arc-cros-gralloc": {TARGET: 2},
    "media-libs/arc-mesa-virgl": {TARGET: 8},
    "media-libs/clpeak": {TARGET: 4},
    "media-libs/clvk": {TARGET: 32},
    "media-libs/clvk-test": {TARGET: 2},
    "media-libs/cros-camera-app": {TARGET: 2},
    "media-libs/cros-camera-auto-framing-tests": {TARGET: 16},
    "media-libs/cros-camera-basic-ops-perf-tests": {TARGET: 4},
    "media-libs/cros-camera-document-scanning-test": {TARGET: 2},
    "media-libs/cros-camera-effects-sm-tests": {TARGET: 16},
    "media-libs/cros-camera-frame-annotator": {TARGET: 16},
    "media-libs/cros-camera-hal-configs-brya": {TARGET: 2},
    "media-libs/cros-camera-hal-fake": {TARGET: 8},
    "media-libs/cros-camera-hal-intel-ipu6": {TARGET: 32},
    "media-libs/cros-camera-hal-usb": {TARGET: 16},
    "media-libs/cros-camera-hdrnet-tests": {TARGET: 16},
    "media-libs/cros-camera-libcamera_connector_headers": {TARGET: 2},
    "media-libs/cros-camera-libcamera_connector_test": {TARGET: 2},
    "media-libs/cros-camera-libfs": {TARGET: 2},
    "media-libs/cros-camera-libjea_test": {TARGET: 2},
    "media-libs/cros-camera-super-res-dlc": {TARGET: 2},
    "media-libs/cros-camera-super-res-tests": {TARGET: 8},
    "media-libs/cros-camera-sw-privacy-switch-test": {TARGET: 16},
    "media-libs/cros-camera-test": {TARGET: 4},
    "media-libs/cros-camera-tracing": {TARGET: 2},
    "media-libs/cros-camera-usb-tests": {TARGET: 2},
    "media-libs/crota-waves-params": {TARGET: 2},
    "media-libs/dav1d": {TARGET: 4},
    "media-libs/dlm": {TARGET: 32},
    "media-libs/evdi": {TARGET: 2},
    "media-libs/fontconfig": {HOST: 2, TARGET: 2},
    "media-libs/freeimage": {TARGET: 16},
    "media-libs/freetype": {HOST: 2, TARGET: 2},
    "media-libs/giflib": {TARGET: 2},
    "media-libs/gmmlib": {TARGET: 8},
    "media-libs/harfbuzz": {HOST: 8, TARGET: 4},
    "media-libs/intel-ipu6ep-camera-bins": {TARGET: 2},
    "media-libs/kano-xperi-params": {TARGET: 2},
    "media-libs/lcms": {TARGET: 2},
    "media-libs/libaom": {TARGET: 8},
    "media-libs/libepoxy": {TARGET: 2},
    "media-libs/libexif": {TARGET: 2},
    "media-libs/libglvnd": {TARGET: 2},
    "media-libs/libjpeg-turbo": {HOST: 2, TARGET: 4},
    "media-libs/libmtp": {TARGET: 2},
    "media-libs/libogg": {TARGET: 2},
    "media-libs/libpng": {HOST: 4, TARGET: 2},
    "media-libs/libsndfile": {TARGET: 4},
    "media-libs/libsync": {TARGET: 2},
    "media-libs/libv4l": {TARGET: 4},
    "media-libs/libvmaf": {TARGET: 2},
    "media-libs/libvorbis": {TARGET: 2},
    "media-libs/libvpx": {TARGET: 8},
    "media-libs/libyuv": {TARGET: 4},
    "media-libs/libyuv-test": {TARGET: 2},
    "media-libs/mesa-iris": {TARGET: 16},
    "media-libs/mesa-llvmpipe": {TARGET: 8},
    "media-libs/minigbm": {TARGET: 2},
    "media-libs/opencl-cts": {TARGET: 16},
    "media-libs/opencv": {HOST: 16, TARGET: 16},
    "media-libs/openh264": {TARGET: 4},
    "media-libs/openjpeg": {TARGET: 2},
    "media-libs/primus-waves-params": {TARGET: 2},
    "media-libs/sbc": {TARGET: 2},
    "media-libs/siliconmotion": {TARGET: 2},
    "media-libs/skia": {TARGET: 32},
    "media-libs/sof-rtnr-params": {TARGET: 2},
    "media-libs/speex": {TARGET: 2},
    "media-libs/taeko-waves-params": {TARGET: 2},
    "media-libs/taniks-waves-params": {TARGET: 2},
    "media-libs/tarlo-waves-params": {TARGET: 8},
    "media-libs/tiff": {TARGET: 2},
    "media-libs/vell-waves-params": {TARGET: 2},
    "media-libs/virglrenderer": {TARGET: 2},
    "media-libs/vulkan-layers": {TARGET: 32},
    "media-libs/vulkan-loader": {TARGET: 2},
    "media-libs/waffle": {TARGET: 2},
    "media-plugins/alsa-plugins": {TARGET: 2},
    "media-sound/adhd": {TARGET: 8},
    "media-sound/alsa-utils": {TARGET: 2},
    "media-sound/audio_streams": {TARGET: 4},
    "media-sound/audio_streams_conformance_test": {TARGET: 16},
    "media-sound/cras-client": {TARGET: 8},
    "media-sound/cras_rust": {TARGET: 8},
    "media-sound/cros_alsa": {TARGET: 4},
    "media-sound/cros_alsa_derive": {TARGET: 2},
    "media-sound/ffmpeg": {TARGET: 2},
    "media-sound/gsm": {TARGET: 2},
    "media-sound/liblc3": {TARGET: 2},
    "media-sound/nc-ap-dlc": {TARGET: 2},
    "media-sound/nuance-dlc": {TARGET: 2},
    "media-sound/sof-tools": {TARGET: 2},
    "media-sound/sof_sys": {TARGET: 2},
    "media-sound/sound_card_init": {TARGET: 8},
    "media-sound/sox": {TARGET: 2},
    "media-sound/sr-bt-dlc": {TARGET: 2},
    "media-tv/v4l-utils": {TARGET: 2},
    "media-video/ffmpeg": {TARGET: 8},
    "media-video/libva-utils": {TARGET: 2},
    "media-video/yavta": {TARGET: 2},
    "net-analyzer/netcat": {TARGET: 2},
    "net-analyzer/netdata": {TARGET: 4},
    "net-analyzer/netperf": {TARGET: 2},
    "net-analyzer/speedtest-cli": {TARGET: 2},
    "net-analyzer/tcpdump": {TARGET: 4},
    "net-analyzer/traceroute": {TARGET: 2},
    "net-analyzer/wireshark": {TARGET: 16},
    "net-dialup/lrzsz": {TARGET: 2},
    "net-dialup/minicom": {TARGET: 2},
    "net-dialup/ppp": {TARGET: 2},
    "net-dialup/ppp-scripts": {TARGET: 2},
    "net-dialup/xl2tpd": {TARGET: 2},
    "net-dns/avahi": {TARGET: 2},
    "net-dns/avahi-daemon": {TARGET: 2},
    "net-dns/bind-tools": {TARGET: 2},
    "net-dns/c-ares": {HOST: 2, TARGET: 2},
    "net-dns/dnsmasq": {TARGET: 2},
    "net-dns/libidn2": {HOST: 2, TARGET: 2},
    "net-firewall/conntrack-tools": {TARGET: 2},
    "net-firewall/iptables": {HOST: 2, TARGET: 2},
    "net-fs/sshfs": {TARGET: 2},
    "net-libs/glib-networking": {TARGET: 2},
    "net-libs/gnutls": {HOST: 2, TARGET: 2},
    "net-libs/grpc": {HOST: 32, TARGET: 32},
    "net-libs/libiio": {TARGET: 2},
    "net-libs/libmbim": {TARGET: 4},
    "net-libs/libmicrohttpd": {TARGET: 2},
    "net-libs/libmnl": {HOST: 2, TARGET: 2},
    "net-libs/libnetfilter_conntrack": {TARGET: 2},
    "net-libs/libnetfilter_cthelper": {TARGET: 2},
    "net-libs/libnetfilter_cttimeout": {TARGET: 2},
    "net-libs/libnetfilter_queue": {TARGET: 2},
    "net-libs/libnfnetlink": {TARGET: 2},
    "net-libs/libpcap": {TARGET: 2},
    "net-libs/libpsl": {HOST: 2, TARGET: 2},
    "net-libs/libqmi": {TARGET: 4},
    "net-libs/libslirp": {HOST: 2},
    "net-libs/libsoup": {TARGET: 2},
    "net-libs/libtirpc": {TARGET: 2},
    "net-libs/libvncserver": {TARGET: 2},
    "net-libs/nghttp2": {TARGET: 2},
    "net-libs/rpcsvc-proto": {HOST: 2, TARGET: 2},
    "net-misc/bridge-utils": {TARGET: 2},
    "net-misc/curl": {HOST: 2, TARGET: 2},
    "net-misc/dhcp": {TARGET: 2},
    "net-misc/dhcpcd-legacy": {TARGET: 2},
    "net-misc/fibocom-tools": {TARGET: 32},
    "net-misc/htpdate": {TARGET: 2},
    "net-misc/iperf": {TARGET: 2},
    "net-misc/iputils": {TARGET: 2},
    "net-misc/modemmanager-next": {TARGET: 4},
    "net-misc/openssh": {TARGET: 2},
    "net-misc/qdl": {TARGET: 2},
    "net-misc/qlog": {TARGET: 2},
    "net-misc/radvd": {TARGET: 2},
    "net-misc/rsync": {HOST: 2, TARGET: 2},
    "net-misc/socat": {TARGET: 2},
    "net-misc/sslh": {TARGET: 2},
    "net-misc/tlsdate": {TARGET: 2},
    "net-misc/usbip": {TARGET: 2},
    "net-misc/wget": {TARGET: 2},
    "net-nds/openldap": {TARGET: 2},
    "net-print/brother_mlaser": {TARGET: 2},
    "net-print/cups": {TARGET: 2},
    "net-print/cups-filters": {TARGET: 2},
    "net-print/cups_proxy": {TARGET: 4},
    "net-print/dymo-cups-drivers": {TARGET: 2},
    "net-print/epson-inkjet-printer-escpr": {TARGET: 2},
    "net-print/epson-receipt-printer-thermal": {TARGET: 2},
    "net-print/fuji-xerox-printing-license": {TARGET: 4},
    "net-print/fujifilm-printing-license": {TARGET: 2},
    "net-print/hplip": {TARGET: 2},
    "net-print/hplip-plugin": {TARGET: 2},
    "net-print/ippsample": {TARGET: 2},
    "net-print/konica-minolta-printing-license": {TARGET: 2},
    "net-print/nec-printing-license": {TARGET: 2},
    "net-print/pwgtocanonij": {TARGET: 2},
    "net-print/starcupsdrv": {TARGET: 2},
    "net-print/xerox-printing-license": {TARGET: 2},
    "net-proxy/tayga": {TARGET: 2},
    "net-proxy/tinyproxy": {TARGET: 2},
    "net-vpn/openvpn": {TARGET: 2},
    "net-vpn/strongswan": {TARGET: 4},
    "net-vpn/wireguard-tools": {TARGET: 2},
    "net-wireless/ax211-updater": {TARGET: 2},
    "net-wireless/bluez": {TARGET: 4},
    "net-wireless/crda": {TARGET: 2},
    "net-wireless/floss": {TARGET: 32},
    "net-wireless/floss_tools": {HOST: 4},
    "net-wireless/hostap-test": {TARGET: 8},
    "net-wireless/hostapd": {TARGET: 8},
    "net-wireless/iw": {TARGET: 2},
    "net-wireless/wireless-regdb": {TARGET: 2},
    "net-wireless/wireless-tools": {TARGET: 2},
    "net-wireless/wpa_supplicant-cros": {TARGET: 4},
    "perl-core/Compress-Raw-Zlib": {HOST: 2},
    "perl-core/File-Temp": {HOST: 2},
    "sci-libs/gsl": {TARGET: 2},
    "sci-libs/tensorflow": {TARGET: 16},
    "sys-apps/acl": {HOST: 2, TARGET: 2},
    "sys-apps/ap_wpsr": {TARGET: 2},
    "sys-apps/attr": {HOST: 2, TARGET: 2},
    "sys-apps/baselayout": {HOST: 2, TARGET: 2},
    "sys-apps/baselayout-java": {HOST: 2},
    "sys-apps/busybox": {TARGET: 2},
    "sys-apps/checkpolicy": {HOST: 2},
    "sys-apps/coreboot-utils": {HOST: 4, TARGET: 4},
    "sys-apps/coreutils": {HOST: 2, TARGET: 2},
    "sys-apps/crosec-legacy-drv": {TARGET: 2},
    "sys-apps/dbus": {HOST: 2, TARGET: 2},
    "sys-apps/debianutils": {HOST: 2, TARGET: 2},
    "sys-apps/diffutils": {HOST: 2, TARGET: 2},
    "sys-apps/dmidecode": {HOST: 2, TARGET: 2},
    "sys-apps/dtc": {HOST: 4, TARGET: 2},
    "sys-apps/ethtool": {TARGET: 2},
    "sys-apps/etphidiap": {TARGET: 2},
    "sys-apps/file": {HOST: 2, TARGET: 2},
    "sys-apps/findutils": {HOST: 2, TARGET: 2},
    "sys-apps/flashmap": {TARGET: 2},
    "sys-apps/flashrom": {HOST: 2, TARGET: 2},
    "sys-apps/flashrom-tester": {TARGET: 8},
    "sys-apps/frecon": {TARGET: 2},
    "sys-apps/fwupd": {TARGET: 4},
    "sys-apps/gawk": {HOST: 2, TARGET: 2},
    "sys-apps/gentoo-functions": {HOST: 2, TARGET: 2},
    "sys-apps/grep": {HOST: 2, TARGET: 2},
    "sys-apps/groff": {HOST: 2, TARGET: 2},
    "sys-apps/hdparm": {TARGET: 2},
    "sys-apps/help2man": {HOST: 2},
    "sys-apps/hwdata": {HOST: 2, TARGET: 2},
    "sys-apps/i2c-tools": {TARGET: 2},
    "sys-apps/install-xattr": {HOST: 2, TARGET: 2},
    "sys-apps/iotools": {TARGET: 2},
    "sys-apps/iproute2": {HOST: 2, TARGET: 2},
    "sys-apps/kexec-lite": {TARGET: 2},
    "sys-apps/keyutils": {TARGET: 2},
    "sys-apps/kmod": {HOST: 2, TARGET: 2},
    "sys-apps/less": {TARGET: 2},
    "sys-apps/libtsm": {TARGET: 2},
    "sys-apps/lshw": {TARGET: 8},
    "sys-apps/mawk": {TARGET: 2},
    "sys-apps/memtester": {TARGET: 2},
    "sys-apps/mmc-utils": {TARGET: 2},
    "sys-apps/mosys": {TARGET: 2},
    "sys-apps/net-tools": {TARGET: 2},
    "sys-apps/nvme-cli": {TARGET: 2},
    "sys-apps/pciutils": {HOST: 2, TARGET: 2},
    "sys-apps/portage": {HOST: 2, TARGET: 2},
    "sys-apps/proot": {HOST: 2},
    "sys-apps/pv": {TARGET: 2},
    "sys-apps/restorecon": {TARGET: 2},
    "sys-apps/rootdev": {TARGET: 2},
    "sys-apps/sandbox": {HOST: 2},
    "sys-apps/secilc": {HOST: 2},
    "sys-apps/sed": {HOST: 2, TARGET: 2},
    "sys-apps/sg3_utils": {TARGET: 4},
    "sys-apps/shadow": {TARGET: 2},
    "sys-apps/smartmontools": {TARGET: 2},
    "sys-apps/systemd-utils": {TARGET: 2},
    "sys-apps/texinfo": {HOST: 2},
    "sys-apps/toybox": {TARGET: 2},
    "sys-apps/ufs-utils": {TARGET: 2},
    "sys-apps/upstart": {TARGET: 2},
    "sys-apps/ureadahead": {TARGET: 2},
    "sys-apps/usbguard": {TARGET: 4},
    "sys-apps/usbutils": {TARGET: 2},
    "sys-apps/util-linux": {HOST: 4, TARGET: 2},
    "sys-apps/which": {HOST: 2, TARGET: 2},
    "sys-auth/nss-mdns": {TARGET: 2},
    "sys-auth/pam_pwdfile": {TARGET: 4},
    "sys-auth/pambase": {TARGET: 2},
    "sys-block/blktrace": {TARGET: 2},
    "sys-block/fio": {TARGET: 2},
    "sys-block/parted": {TARGET: 2},
    "sys-block/thin-provisioning-tools": {TARGET: 4},
    "sys-boot/chromeos-bmpblk": {TARGET: 4},
    "sys-boot/chromeos-bootimage": {TARGET: 2},
    "sys-boot/coreboot": {TARGET: 32},
    "sys-boot/coreboot-private-files-baseboard-brya": {TARGET: 2},
    "sys-boot/depthcharge": {TARGET: 4},
    "sys-boot/firmware-bootsplash-assets": {TARGET: 2},
    "sys-boot/gnu-efi": {TARGET: 2},
    "sys-boot/intel-adlfsp": {TARGET: 2},
    "sys-boot/intel-rplfsp": {TARGET: 2},
    "sys-boot/kdump-init": {TARGET: 2},
    "sys-boot/libpayload": {TARGET: 2},
    "sys-boot/syslinux": {TARGET: 4},
    "sys-boot/u-boot": {TARGET: 4},
    "sys-cluster/fcp": {TARGET: 32},
    "sys-cluster/libqb": {TARGET: 2},
    "sys-devel/aapt": {HOST: 2},
    "sys-devel/arc-build": {TARGET: 2},
    "sys-devel/arc-toolchain-p": {HOST: 2},
    "sys-devel/arc-toolchain-t": {HOST: 2},
    "sys-devel/autoconf": {HOST: 2},
    "sys-devel/autoconf-archive": {HOST: 2, TARGET: 2},
    "sys-devel/autoconf-wrapper": {HOST: 2},
    "sys-devel/automake": {HOST: 2},
    "sys-devel/automake-wrapper": {HOST: 4},
    "sys-devel/bc": {HOST: 4, TARGET: 2},
    "sys-devel/binutils": {HOST: 4, TARGET: 4},
    "sys-devel/binutils-config": {HOST: 2, TARGET: 2},
    "sys-devel/bison": {HOST: 2},
    "sys-devel/crash": {TARGET: 32},
    "sys-devel/crossdev": {HOST: 2},
    "sys-devel/flex": {HOST: 2, TARGET: 2},
    "sys-devel/gcc": {HOST: 8},
    "sys-devel/gcc-config": {HOST: 2},
    "sys-devel/gdb": {TARGET: 8},
    "sys-devel/gettext": {HOST: 2},
    "sys-devel/gnuconfig": {HOST: 4},
    "sys-devel/grit-i18n": {HOST: 2},
    "sys-devel/libtool": {HOST: 2},
    "sys-devel/llvm": {TARGET: 32},
    "sys-devel/m4": {HOST: 2},
    "sys-devel/make": {HOST: 2},
    "sys-devel/patch": {HOST: 2, TARGET: 4},
    "sys-devel/zipalign": {HOST: 2},
    "sys-firmware/adl-ucode-firmware-private": {TARGET: 2},
    "sys-firmware/brya-kernel-ucode": {TARGET: 2},
    "sys-firmware/chromeos-fpmcu-release-bloonchipper": {TARGET: 2},
    "sys-firmware/chromeos-fpmcu-release-buccaneer": {TARGET: 4},
    "sys-firmware/chromeos-fpmcu-release-dartmonkey": {TARGET: 2},
    "sys-firmware/chromeos-fpmcu-release-helipilot": {TARGET: 2},
    "sys-firmware/chromeos-zephyr-fpmcu-release-bloonchipper": {TARGET: 8},
    "sys-firmware/edk2-ovmf-bin": {HOST: 4},
    "sys-firmware/edk2-ovmf-crosvm": {TARGET: 4},
    "sys-firmware/fwupd-camera": {TARGET: 2},
    "sys-firmware/fwupd-peripherals": {TARGET: 2},
    "sys-firmware/fwupd-storage": {TARGET: 2},
    "sys-firmware/ipxe": {HOST: 4},
    "sys-firmware/mmc-firmware": {TARGET: 2},
    "sys-firmware/parade-ps8815a2-firmware": {TARGET: 4},
    "sys-firmware/rpl-ucode-firmware-private": {TARGET: 2},
    "sys-firmware/seabios-bin": {HOST: 8},
    "sys-firmware/servo-firmware": {TARGET: 2},
    "sys-firmware/sgabios": {HOST: 4},
    "sys-firmware/sunplus-fwverify": {TARGET: 4},
    "sys-fs/cryptsetup": {TARGET: 2},
    "sys-fs/dosfstools": {TARGET: 2},
    "sys-fs/e2fsprogs": {HOST: 4, TARGET: 2},
    "sys-fs/ecryptfs-utils": {TARGET: 2},
    "sys-fs/erofs-utils": {TARGET: 2},
    "sys-fs/exfat-utils": {TARGET: 2},
    "sys-fs/fscryptctl": {TARGET: 2},
    "sys-fs/fuse": {TARGET: 2},
    "sys-fs/fuse-archive": {TARGET: 2},
    "sys-fs/fuse-common": {TARGET: 2},
    "sys-fs/fuse-exfat": {TARGET: 2},
    "sys-fs/lvm2": {TARGET: 2},
    "sys-fs/mount-zip": {TARGET: 2},
    "sys-fs/mtd-utils": {TARGET: 2},
    "sys-fs/mtools": {TARGET: 2},
    "sys-fs/ntfs3g": {TARGET: 2},
    "sys-fs/rar2fs": {TARGET: 2},
    "sys-fs/squashfs-tools": {HOST: 2, TARGET: 2},
    "sys-fs/udev": {HOST: 4, TARGET: 2},
    "sys-fs/xfsprogs": {TARGET: 4},
    "sys-kernel/arcvm-kernel-ack-5_10": {TARGET: 32},
    "sys-kernel/chromeos-kernel-5_15": {TARGET: 16},
    "sys-kernel/linux-firmware": {TARGET: 2},
    "sys-kernel/linux-firmware-builtin": {TARGET: 2},
    "sys-kernel/linux-headers": {HOST: 2, TARGET: 2},
    "sys-libs/binutils-libs": {TARGET: 4},
    "sys-libs/gcc-libs": {TARGET: 2},
    "sys-libs/gdbm": {TARGET: 2},
    "sys-libs/glibc": {HOST: 8},
    "sys-libs/ldb": {TARGET: 2},
    "sys-libs/libcap": {HOST: 2, TARGET: 2},
    "sys-libs/libcap-ng": {HOST: 2, TARGET: 2},
    "sys-libs/libcxx": {HOST: 4, TARGET: 4},
    "sys-libs/libnih": {HOST: 2, TARGET: 2},
    "sys-libs/libnvme": {TARGET: 2},
    "sys-libs/libseccomp": {HOST: 2},
    "sys-libs/libselinux": {HOST: 2, TARGET: 2},
    "sys-libs/libsepol": {HOST: 2, TARGET: 8},
    "sys-libs/libxcrypt": {HOST: 2, TARGET: 2},
    "sys-libs/llvm-libunwind": {HOST: 2, TARGET: 2},
    "sys-libs/ncurses": {HOST: 2, TARGET: 2},
    "sys-libs/pam": {TARGET: 2},
    "sys-libs/readline": {HOST: 2, TARGET: 2},
    "sys-libs/scudo": {TARGET: 4},
    "sys-libs/talloc": {HOST: 2, TARGET: 2},
    "sys-libs/tdb": {TARGET: 2},
    "sys-libs/tevent": {TARGET: 2},
    "sys-libs/timezone-data": {TARGET: 2},
    "sys-libs/zlib": {HOST: 2, TARGET: 2},
    "sys-power/dptf": {TARGET: 32},
    "sys-power/dptf-policy-active2": {TARGET: 2},
    "sys-power/dptf-policy-ap": {TARGET: 2},
    "sys-power/dptf-policy-passive2": {TARGET: 2},
    "sys-power/dptf-policy-rfim": {TARGET: 2},
    "sys-power/dptf-policy-vs": {TARGET: 2},
    "sys-power/iasl": {HOST: 16, TARGET: 8},
    "sys-power/powertop": {TARGET: 4},
    "sys-power/uhubctl": {TARGET: 2},
    "sys-process/audit": {TARGET: 2},
    "sys-process/iotop": {TARGET: 2},
    "sys-process/lsof": {HOST: 2, TARGET: 2},
    "sys-process/numactl": {TARGET: 2},
    "sys-process/procps": {HOST: 2, TARGET: 2},
    "sys-process/psmisc": {HOST: 2, TARGET: 2},
    "sys-process/time": {TARGET: 2},
    "sys-process/usbtop": {TARGET: 2},
    "virtual/acl": {HOST: 4, TARGET: 2},
    "virtual/arc-media-profiles": {TARGET: 2},
    "virtual/arcvm-codec": {TARGET: 2},
    "virtual/assets": {TARGET: 2},
    "virtual/autotest-assistant-libs": {TARGET: 2},
    "virtual/autotest-capability": {TARGET: 2},
    "virtual/autotest-libs": {TARGET: 2},
    "virtual/autotest-private-libs": {TARGET: 2},
    "virtual/autotest-tests": {TARGET: 2},
    "virtual/awk": {HOST: 2, TARGET: 2},
    "virtual/bindgen": {TARGET: 2},
    "virtual/cheets": {TARGET: 2},
    "virtual/chromeos-activate-date": {TARGET: 2},
    "virtual/chromeos-audio-nc-ap-dlc": {TARGET: 2},
    "virtual/chromeos-audio-nuance-dlc": {TARGET: 2},
    "virtual/chromeos-auth-config": {TARGET: 2},
    "virtual/chromeos-board-default-apps": {TARGET: 2},
    "virtual/chromeos-bootcomplete": {TARGET: 2},
    "virtual/chromeos-bsp": {TARGET: 2},
    "virtual/chromeos-bsp-dev": {TARGET: 2},
    "virtual/chromeos-bsp-dev-root": {TARGET: 2},
    "virtual/chromeos-bsp-factory": {TARGET: 2},
    "virtual/chromeos-bsp-test": {TARGET: 2},
    "virtual/chromeos-bsp-test-root": {TARGET: 2},
    "virtual/chromeos-ec-driver-init": {TARGET: 2},
    "virtual/chromeos-ec-private-files": {TARGET: 2},
    "virtual/chromeos-ec-touch-firmware": {TARGET: 4},
    "virtual/chromeos-firewall": {TARGET: 2},
    "virtual/chromeos-firmware": {TARGET: 2},
    "virtual/chromeos-firmware-fpmcu": {TARGET: 2},
    "virtual/chromeos-fpmcu-test": {TARGET: 2},
    "virtual/chromeos-fpmcu-unittests": {TARGET: 2},
    "virtual/chromeos-interface": {TARGET: 2},
    "virtual/chromeos-printing": {TARGET: 2},
    "virtual/chromeos-regions": {TARGET: 2},
    "virtual/chromeos-soda-models": {TARGET: 2},
    "virtual/chromeos-test-testauthkeys": {TARGET: 2},
    "virtual/chromium-os-printing": {TARGET: 2},
    "virtual/coreboot-private-files": {TARGET: 2},
    "virtual/cros-camera-hal": {TARGET: 2},
    "virtual/cros-camera-hal-configs": {TARGET: 2},
    "virtual/dptf": {TARGET: 2},
    "virtual/editor": {TARGET: 2},
    "virtual/factory-deps": {TARGET: 2},
    "virtual/implicit-system": {TARGET: 2},
    "virtual/jdk": {HOST: 2},
    "virtual/jpeg": {HOST: 2, TARGET: 2},
    "virtual/jpeg-compat": {HOST: 2},
    "virtual/jre": {HOST: 4},
    "virtual/krb5": {TARGET: 2},
    "virtual/libc": {HOST: 2, TARGET: 2},
    "virtual/libcrypt": {HOST: 2, TARGET: 2},
    "virtual/libelf": {HOST: 2, TARGET: 2},
    "virtual/libgudev": {TARGET: 2},
    "virtual/libiconv": {HOST: 2, TARGET: 2},
    "virtual/libintl": {HOST: 2, TARGET: 2},
    "virtual/libudev": {TARGET: 2},
    "virtual/libusb": {HOST: 2, TARGET: 2},
    "virtual/linux-sources": {TARGET: 2},
    "virtual/logger": {TARGET: 2},
    "virtual/opengles": {TARGET: 2},
    "virtual/os-headers": {HOST: 2, TARGET: 2},
    "virtual/package-manager": {HOST: 2},
    "virtual/perl-CPAN-Meta-Requirements": {HOST: 2},
    "virtual/perl-Carp": {HOST: 2},
    "virtual/perl-Compress-Raw-Bzip2": {HOST: 4},
    "virtual/perl-Compress-Raw-Zlib": {HOST: 2},
    "virtual/perl-Data-Dumper": {HOST: 2},
    "virtual/perl-Digest-MD5": {HOST: 4},
    "virtual/perl-Encode": {HOST: 2},
    "virtual/perl-Exporter": {HOST: 2},
    "virtual/perl-ExtUtils-MakeMaker": {HOST: 2},
    "virtual/perl-File-Spec": {HOST: 4},
    "virtual/perl-File-Temp": {HOST: 2},
    "virtual/perl-Getopt-Long": {HOST: 2},
    "virtual/perl-IO": {HOST: 4},
    "virtual/perl-IO-Compress": {HOST: 4},
    "virtual/perl-MIME-Base64": {HOST: 2},
    "virtual/perl-Module-Metadata": {HOST: 4},
    "virtual/perl-Scalar-List-Utils": {HOST: 4},
    "virtual/perl-Time-Local": {HOST: 2},
    "virtual/perl-XSLoader": {HOST: 4},
    "virtual/perl-libnet": {HOST: 8},
    "virtual/perl-parent": {HOST: 4},
    "virtual/pita": {TARGET: 4},
    "virtual/pkgconfig": {HOST: 2, TARGET: 2},
    "virtual/python-cffi": {TARGET: 2},
    "virtual/rust": {HOST: 2, TARGET: 2},
    "virtual/rust-binaries": {HOST: 4, TARGET: 2},
    "virtual/secagentd": {TARGET: 2},
    "virtual/service-manager": {TARGET: 2},
    "virtual/servo-config-dut-usb3": {TARGET: 2},
    "virtual/target-chrome-os": {TARGET: 2},
    "virtual/target-chrome-os-test": {TARGET: 2},
    "virtual/target-chromium-os": {TARGET: 2},
    "virtual/target-chromium-os-dev": {TARGET: 2},
    "virtual/target-chromium-os-factory": {TARGET: 2},
    "virtual/target-chromium-os-factory-shim": {TARGET: 2},
    "virtual/target-chromium-os-test": {TARGET: 2},
    "virtual/target-os": {TARGET: 2},
    "virtual/target-os-dev": {TARGET: 2},
    "virtual/target-os-factory": {TARGET: 2},
    "virtual/target-os-factory-shim": {TARGET: 2},
    "virtual/target-os-test": {TARGET: 2},
    "virtual/target-sdk-implicit-system": {HOST: 2},
    "virtual/tast-local-tests": {TARGET: 2},
    "virtual/tast-remote-tests": {TARGET: 2},
    "virtual/tmpfiles": {HOST: 2, TARGET: 2},
    "virtual/ttf-fonts": {TARGET: 2},
    "virtual/udev": {HOST: 4, TARGET: 2},
    "virtual/update-policy": {TARGET: 2},
    "virtual/vulkan-icd": {TARGET: 2},
    "virtual/wpa_supplicant": {TARGET: 2},
    "virtual/yacc": {HOST: 2},
    "www-apps/novnc": {TARGET: 2},
    "x11-apps/igt-gpu-tools": {TARGET: 4},
    "x11-base/xcb-proto": {HOST: 2, TARGET: 2},
    "x11-base/xorg-proto": {TARGET: 2},
    "x11-drivers/opengles-headers": {TARGET: 2},
    "x11-drivers/touchpad-tests": {TARGET: 2},
    "x11-libs/arc-libdrm": {TARGET: 2},
    "x11-libs/cairo": {HOST: 2, TARGET: 4},
    "x11-libs/gdk-pixbuf": {HOST: 2, TARGET: 2},
    "x11-libs/libX11": {TARGET: 2},
    "x11-libs/libXau": {TARGET: 2},
    "x11-libs/libXdmcp": {TARGET: 2},
    "x11-libs/libdrm": {TARGET: 2},
    "x11-libs/libpciaccess": {TARGET: 2},
    "x11-libs/libva": {TARGET: 2},
    "x11-libs/libva-intel-media-driver": {TARGET: 32},
    "x11-libs/libxcb": {TARGET: 2},
    "x11-libs/libxkbcommon": {TARGET: 2},
    "x11-libs/pango": {TARGET: 2},
    "x11-libs/pixman": {HOST: 4, TARGET: 2},
    "x11-libs/xtrans": {TARGET: 2},
    "x11-misc/compose-tables": {TARGET: 2},
    "x11-misc/read-edid": {TARGET: 2},
    "x11-misc/shared-mime-info": {HOST: 2, TARGET: 2},
    "x11-misc/util-macros": {HOST: 2, TARGET: 2},
    "x11-misc/xkeyboard-config": {TARGET: 2},
}
