load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "xpak",
    srcs = ["xpak.go"],
    importpath = "cros.local/ebuild/private/common/portage/xpak",
    visibility = ["//ebuild:__subpackages__"],
)
