[package]
name = "build_image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cliutil = { path = "../../common/cliutil" }
container = { path = "../../common/container" }
makechroot = { path = "../../common/makechroot" }
binarypackage = { path = "../../common/portage/binarypackage" }

anyhow.workspace = true
clap.workspace = true
runfiles.workspace = true
users.workspace = true
