[package]
name = "process_artifacts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap.workspace = true
itertools.workspace = true
prost.workspace = true
prost-types.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
zstd.workspace = true

[dev-dependencies]
runfiles.workspace = true
walkdir.workspace = true

[build-dependencies]
prost-build.workspace = true
