load("//ebuild:defs.bzl", "ebuild")

ebuild(
    name = "ethtool",
    src = "ethtool-4.13.ebuild",
    category = "sys-apps",
    distfiles = {
        "@ethtool_4_13//file": "ethtool-4.13.tar.xz",
    },
)
