load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "runfiles",
    srcs = ["runfiles.go"],
    importpath = "cros.local/ebuild/private/common/runfiles",
    visibility = ["//visibility:public"],
)
