[package]
name = "durabletree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fileutil = { path = "../fileutil" }

anyhow.workspace = true
itertools.workspace = true
nix.workspace = true
serde.workspace = true
serde_json.workspace = true
tar.workspace = true
tempfile.workspace = true
tracing.workspace = true
walkdir.workspace = true
xattr.workspace = true
zstd.workspace = true

[dev-dependencies]
hex.workspace = true
sha2.workspace = true
