[package]
name = "sdk_from_archive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
processes = { path = "../../common/processes" }
tar = { path = "../../common/tar" }

anyhow.workspace = true
clap.workspace = true
