#!/bin/bash
# Copyright 2022 The ChromiumOS Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -eu -o pipefail

# Add users go path before trying
if GO="$(command -v go)"; then
    # Add /bin to every entry in gopath.
    PATH="${PATH}:$("$GO" env GOPATH | sed 's/:/\/bin:/g')/bin"
fi

# Allow users to create a bazelrc file shared between all chromiumos checkouts.
# ~/.bazelrc is also shared between all chromiumos checkouts, but it also has
# non-chromiumos stuff.
ARGS=()
if [ -e "$HOME/.chromiumos.bazelrc" ]; then
  ARGS+=("--bazelrc=$HOME/.chromiumos.bazelrc")
fi

if BAZELISK="$(command -v bazelisk)"; then
    exec "${BAZELISK}" "${ARGS[@]}" "$@"
fi

echo "Bazelisk was not found. Please install using the following command:" 1>&2
echo "> go install github.com/bazelbuild/bazelisk@latest" 1>&2

exit 1
