[package]
name = "drive_binary_package"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
vdb = { path = "../../common/portage/vdb" }
anyhow.workspace = true
runfiles.workspace = true
tempfile.workspace = true
