[package]
name = "xpaktool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cliutil = { path = "../../common/cliutil" }
binarypackage = { path = "../../common/portage/binarypackage" }

anyhow.workspace = true
bzip2.workspace = true
clap.workspace = true
infer.workspace = true
itertools.workspace = true
lazy_static.workspace = true
rayon.workspace = true
regex.workspace = true
tempfile.workspace = true
walkdir.workspace = true

[dev-dependencies]
runfiles.workspace = true
