[package]
name = "binarypackage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cliutil = { path = "../../cliutil" }

anyhow.workspace = true
bytes.workspace = true
nix.workspace = true
tar.workspace = true
zstd.workspace = true

[dev-dependencies]
runfiles.workspace = true
tempfile.workspace = true
