[package]
name = "cliutil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-chrome-trace = { path = "../tracing-chrome-trace" }
fileutil = { path = "../fileutil" }

anyhow.workspace = true
clap.workspace = true
either.workspace = true
itertools.workspace = true
nix.workspace = true
shell-escape.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
regex.workspace = true
runfiles.workspace = true
tempfile.workspace = true
