[package]
name = "cliutil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing_chrome_trace = { path = "../tracing_chrome_trace" }
fileutil = { path = "../fileutil" }

anyhow.workspace = true
clap.workspace = true
itertools.workspace = true
nix.workspace = true
shell_escape.workspace = true
tracing.workspace = true
tracing_subscriber.workspace = true

[dev-dependencies]
regex.workspace = true
runfiles.workspace = true
tempfile.workspace = true
