[package]
name = "ide-support"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
by_address.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
runfiles.workspace = true
serde_json.workspace = true

[lib]
name = "on_save"
path = "on_save.rs"

[[bin]]
name = "gen_rust_project"
path = "gen_rust_project.rs"
