load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "profile",
    srcs = ["profile.go"],
    importpath = "cros.local/rules_ebuild/ebuild/private/common/standard/profile",
    visibility = ["//visibility:public"],
    deps = ["//ebuild/private/common/standard/makevars"],
)
