load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "fileutil",
    srcs = [
        "copy.go",
        "dualpath.go",
    ],
    importpath = "cros.local/bazel/ebuild/private/common/fileutil",
    visibility = ["//visibility:public"],
)
