# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

visibility("public")

def get_output_dir(ctx):
    # A random filename that's unlikely to collide with anything generated by
    # another rule.
    root_file = ctx.actions.declare_file(ctx.label.name + "_ROOT_OENTSUH")

    # Otherwise bazel will complain that it doesn't have a value.
    ctx.actions.write(root_file, "")
    return root_file.dirname
