# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#load(":toolchain.bzl", "generate_emulation_toolchains")
#
#package(default_visibility = ["//visibility:public"])
#
#generate_emulation_toolchains()
#
#toolchain_type(
#    name = "toolchain_type",
#)
