[package]
name = "processes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/processes.rs"

[dependencies]
anyhow.workspace = true
nix.workspace = true
signal-hook.workspace = true
