[package]
name = "build_package"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cliutil = { path = "../../common/cliutil" }
container = { path = "../../common/container" }

anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
nix.workspace = true
rand.workspace = true
runfiles.workspace = true
serde.workspace = true
serde_json.workspace = true
