# This file is used to generate your workspace-level Cargo.toml.

[package]
name = "dummy"
version = "0.1.0"
edition = "2021"

# Ensure that it doesn't get pulled into another cargo workspace.
[workspace]

[dependencies]
anyhow = { version = "1.0.66", features = ["backtrace"] }
base64 = "0.20.0"
bytes = "0.4.12"
by_address = "1.1.0"
bzip2 = "0.4.4"
clap = { version = "4.0.29", features = ["derive"] }
colored = "2.0.0"
elfloader = "0.16.0"
env_logger = "0.9.3"
flate2 = "1.0"
hex = "0.4.3"
itertools = "0.10.5"
lazy_static = "1.4.0"
libc = "0.2.139"
log = "0.4.17"
md-5 = "0.10.5"
nix = { version = "0.26.1", features = ["fs", "ioctl", "user"] }
nom = "7.1.1"
nom_locate = "4.0.0"
nom-regex = "0.2.0"
once_cell = "1.16.0"
path-absolutize = "3.0.14"
pathdiff = "0.2.1"
proptest = "1.0.0"
rayon = "1.6.0"
regex = "1.7.0"
rpds = "0.12.0"
runfiles = "0.1.0"
scopeguard = "1.1.0"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
sha2 = "0.10.6"
shell-escape = "0.1.5"
signal-hook = "0.3.14"
strum = "0.24.1"
strum_macros = "0.24.3"
tar = "0.4.38"
tempfile = "3.3.0"
tera = { version = "1.17.1", default-features = false }
thiserror = "1.0.37"
tinytemplate = "1.2.1"
topological-sort = "0.2.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
url = "2.3.1"
users = "0.11.0"
walkdir = "2.3.2"
xattr = "1.0.0"
zstd = "0.12.1"
