[package]
name = "dummy"
version = "0.1.0"

# This is a dummy crate. Cargo only adds dependencies in the workspace if a
# crate within that workspace uses it. This dummy crate depends on all workspace
# entries.
[dependencies]
anyhow = { version = "1.0.66", features = ["backtrace"] }
base64 = "0.20.0"
by_address = "1.1.0"
bytes = "0.4.12"
bzip2 = "0.4.4"
# chrono: cargo-bazel doesn't support `default_features = false`
chrono = { version = "0.4.34", features = ["clock"] }
clap = { version = "4.0.29", features = ["derive"] }
colored = "2.0.0"
env_logger = "0.9.3"
flate2 = "1.0"
grpc = "0.6.2"
hex = "0.4.3"
itertools = "0.10.5"
lazy_static = "1.4.0"
libc = "0.2.139"
log = "0.4.17"
# Despite the fact that md-5 uses a "-", you use it in rust as md5::*.
# If we follow conventions and rename it to md_5 with an alias, then in the rust
# code the name changes to md_5::*.
md5 = { package = "md-5", version = "0.10.5" }
nix = { version = "0.26.1", features = ["fs", "ioctl"] }
nom = "7.1.1"
nom_regex = { package = "nom-regex", version = "0.2.0" }
nom_locate = "4.0.0"
once_cell = "1.16.0"
path_absolutize = { package = "path-absolutize", version = "3.0.14" }
pathdiff = "0.2.1"
pretty_assertions = "1.1.0"
proptest = "1.0.0"
prost = "0.12.4"
prost-build = "0.12.4"
prost-types = "0.12.4"
protoc-gen-prost = "0.3.1"
protoc-gen-tonic = "0.4.0"
protobuf = { version = "2.8.2", features = ["with-bytes"] }
rand = "0.8.5"
rayon = "1.6.0"
regex = "1.7.0"
rpds = "0.12.0"
scopeguard = "1.1.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.89"
sha2 = "0.10.6"
shell_escape = { package = "shell-escape", version = "0.1.5" }
signal_hook = {package = "signal-hook", version = "0.3.14" }
strum = "0.24.1"
strum_macros = "0.24.3"
tar = "0.4.38"
tempfile = "3.3.0"
tera = { version = "1.19.1", default-features = false }
thiserror = "1.0.37"
tinytemplate = "1.2.1"
tls-api = "0.1.22"
tls-api-stub = "0.1.22"
toml = "0.8.8"
tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = "0.1.15"
tonic = "0.11.0"
tracing = "0.1.37"
tracing_chrome = { package = "tracing-chrome", version = "0.7.1" }
tracing_subscriber = { package = "tracing-subscriber", version = "0.3.17", features = ["env-filter", "json"] }
url = "2.3.1"
users = "0.11.0"
walkdir = "2.3.2"
xattr = "1.0.0"
zstd = "0.12.1"
