[package]
name = "create_interface_layer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cliutil = { path = "../../common/cliutil" }
container = { path = "../../common/container" }
durabletree = { path = "../../common/durabletree" }
fileutil = { path = "../../common/fileutil" }

anyhow.workspace = true
clap.workspace = true
elf.workspace = true
regex.workspace = true
rayon.workspace = true
tempfile.workspace = true
walkdir.workspace = true
xattr.workspace = true

[dev-dependencies]
testutil = { path = "../../common/testutil" }
runfiles.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
