#!/bin/bash
# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -eu -o pipefail

# We expect BAZEL_REAL to be set by Bazel.
if [[ -z "${BAZEL_REAL:=}" ]]; then
  echo "ERROR: BAZEL_REAL must be set." >&2
  exit 1
fi

# Allow users to create a bazelrc file shared between all chromiumos checkouts.
# ~/.bazelrc is also shared between all chromiumos checkouts, but it also has
# non-chromiumos stuff.
ARGS=()
if [ -e "${HOME}/.chromiumos.bazelrc" ]; then
  ARGS+=("--bazelrc=${HOME}/.chromiumos.bazelrc")
fi

while [[ "$#" -gt 1 ]]; do
  if [[ "$1" == --* ]]; then
    ARGS+=("$1")
    shift
  else
    break
  fi
done

# Used to force the alchemist_digest repo rule to re-run every invocation.
if [[ "$#" -gt 1 ]]; then
  ARGS+=("$1")
  shift
  CACHE_BUST_DATE="${CACHE_BUST_DATE:-$(date --iso-8601=ns)}"
  ARGS+=("--repo_env=_CACHE_BUST_DATE=${CACHE_BUST_DATE}")
fi

# Append the current ci.chromium.org build id, if this is a CI build.
# More info: https://chromium.googlesource.com/infra/luci/luci-py/+/HEAD/client/LUCI_CONTEXT.md
#
# TODO(b/311706335): Read the buildbucket ID from BAPI instead of LUCI_CONTEXT
# when that's available.
if [[ ! -z ${LUCI_CONTEXT:-} ]]; then
  # Match and output the ID group: "invocations/build-<ID>" from the resultDB field.
  BUILDBUCKET_ID=$(cat ${LUCI_CONTEXT} | \
    python3 -c \
    "import sys, json

print(json.load(sys.stdin)['resultdb']['current_invocation']['name'])" | \
    grep -oP "invocations/build-\K(\d+)$")
  ARGS+=("--build_metadata=cros/luci/build_url=https://ci.chromium.org/ui/b/${BUILDBUCKET_ID}")
fi

exec "${BAZEL_REAL}" "${ARGS[@]}" "$@"
