[package]
name = "vdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binarypackage = { path = "../binarypackage" }
anyhow.workspace = true
hex.workspace = true
md5.workspace = true
walkdir.workspace = true

[dev-dependencies]
testutil = { path = "../../testutil" }
runfiles.workspace = true
tempfile.workspace = true
