[package]
name = "alchemist"
version = "0.1.0"
edition = "2021"

[dependencies]
# When you add local dependencies here, remember to update shared_crates.bzl and
# rerun regen-srcs.sh.
cliutil = { path = "../../common/cliutil" }
version = { path = "../../common/portage/version" }

anyhow.workspace = true
base64.workspace = true
clap.workspace = true
colored.workspace = true
hex.workspace = true
itertools.workspace = true
lazy_static.workspace = true
nix.workspace = true
nom.workspace = true
nom_locate.workspace = true
nom_regex.workspace = true
once_cell.workspace = true
rayon.workspace = true
regex.workspace = true
rpds.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
strum.workspace = true
strum_macros.workspace = true
tempfile.workspace = true
tera.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
tracing_chrome.workspace = true
tracing_subscriber.workspace = true
url.workspace = true
walkdir.workspace = true

[dev-dependencies]
testutil = { path = "../../common/testutil" }
runfiles.workspace = true
shell_escape.workspace = true
proptest.workspace = true
pretty_assertions.workspace = true
