[workspace]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
# List third-party deps here.
anyhow = { version = "1.0.66", features = ["backtrace"] }
base64 = "0.20.0"
clap = { version = "4.0.29", features = ["derive"] }
colored = "2.0.0"
hex = "0.4.3"
itertools = "0.10.5"
lazy_static = "1.4.0"
libc = "0.2.139"
nix = { version = "0.26.1", features = ["fs", "ioctl"] }
nom = "7.1.1"
nom_locate = "4.0.0"
nom-regex = "0.2.0"
once_cell = "1.16.0"
pretty_assertions = "1.1.0"
proptest = "1.0.0"
rayon = "1.6.0"
regex = "1.7.0"
rpds = "0.12.0"
runfiles = "0.1.0"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
sha2 = "0.10.6"
shell-escape = "0.1.5"
strum = "0.24.1"
strum_macros = "0.24.3"
tempfile = "3.3.0"
tera = { version = "1.19.1", default-features = false }
thiserror = "1.0.37"
tracing = "0.1.37"
tracing-chrome = "0.7.1"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
url = "2.3.1"
walkdir = "2.3.2"

[package]
name = "alchemist"
version = "0.1.0"
edition = "2021"
default-run = "alchemist"

[dependencies]
# When you add local dependencies here, remember to update shared_crates.bzl and
# rerun regen-srcs.sh.
cliutil = { path = "../../common/cliutil" }
version = { path = "../../common/portage/version" }

anyhow.workspace = true
base64.workspace = true
clap.workspace = true
colored.workspace = true
hex.workspace = true
itertools.workspace = true
lazy_static.workspace = true
nix.workspace = true
nom.workspace = true
nom_locate.workspace = true
nom-regex.workspace = true
once_cell.workspace = true
rayon.workspace = true
regex.workspace = true
rpds.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
strum.workspace = true
strum_macros.workspace = true
tempfile.workspace = true
tera.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-chrome.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
walkdir.workspace = true

[dev-dependencies]
testutil = { path = "../../common/testutil" }
shell-escape.workspace = true
proptest.workspace = true
pretty_assertions.workspace = true
