[package]
name = "common_extract_tarball"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
processes = { path = "../processes" }

anyhow.workspace = true
clap.workspace = true
runfiles.workspace = true
tar.workspace = true
pathdiff.workspace = true
serde.workspace = true

[dev-dependencies]
binarypackage = { path = "../portage/binarypackage" }
fileutil = { path = "../fileutil" }
