[package]
name = "alchemist"
version = "0.1.0"
edition = "2021"
default-run = "alchemist"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.66", features = ["backtrace"] }
clap = { version = "4.0.29", features = ["derive"] }
colored = "2.0.0"
itertools = "0.10.5"
lazy_static = "1.4.0"
nix = "0.26.1"
nom = "7.1.1"
nom_locate = "4.0.0"
nom-regex = "0.2.0"
once_cell = "1.16.0"
rayon = "1.6.0"
regex = "1.7.0"
rpds = "0.12.0"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
strum = "0.24.1"
strum_macros = "0.24.3"
tempfile = "3.3.0"
thiserror = "1.0.37"
url = "2.3.1"
walkdir = "2.3.2"

[dev-dependencies]
proptest = "1.0.0"
