[package]
name = "build_sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cliutil = { path = "../../common/cliutil" }
fileutil = { path = "../../common/fileutil" }
makechroot = { path = "../../common/makechroot" }
mountsdk = { path = "../../common/mountsdk" }

anyhow.workspace = true
clap.workspace = true
runfiles.workspace = true
