[package]
name = "testutil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
libc.workspace = true
once_cell.workspace = true
runfiles.workspace = true

[dev-dependencies]
nix.workspace = true
tempfile.workspace = true
