# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# AUTO GENERATED DO NOT EDIT!
# Regenerate this file using ./regen-srcs.sh
# It should be regenerated each time a file is added or removed.
ALCHEMIST_SRCS = [
    Label("//:Cargo.toml"),
    Label("//bazel/ebuild/private/alchemist:src/analyze/dependency.rs"),
    Label("//bazel/ebuild/private/alchemist:src/analyze/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/analyze/restrict.rs"),
    Label("//bazel/ebuild/private/alchemist:src/analyze/source.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bash/expr/eval.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bash/expr/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bash/expr/parser.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bash/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bash/vars.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/alchemist.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/digest_repo.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/dump_package.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/common.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/internal/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/internal/overlays/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/internal/overlays/templates/chromiumos-overlay.BUILD.bazel"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/internal/overlays/templates/overlay.BUILD.bazel"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/internal/packages/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/internal/packages/templates/package.BUILD.bazel"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/internal/sdk/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/internal/sdk/templates/emerge"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/internal/sdk/templates/pkg-config"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/internal/sdk/templates/portage-tool"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/internal/sdk/templates/sdk.BUILD.bazel"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/internal/sources/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/internal/sources/templates/source.BUILD.bazel"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/public/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/public/templates/package.BUILD.bazel"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/repositories.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/settings.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/templates/repositories.bzl"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/templates/root.BUILD.bazel"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/generate_repo/templates/settings.bzl"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/main.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/ver_rs.rs"),
    Label("//bazel/ebuild/private/alchemist:src/bin/alchemist/ver_test.rs"),
    Label("//bazel/ebuild/private/alchemist:src/common.rs"),
    Label("//bazel/ebuild/private/alchemist:src/config/bundle.rs"),
    Label("//bazel/ebuild/private/alchemist:src/config/makeconf/generate/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/config/makeconf/generate/templates/make.conf"),
    Label("//bazel/ebuild/private/alchemist:src/config/makeconf/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/config/makeconf/parser.rs"),
    Label("//bazel/ebuild/private/alchemist:src/config/miscconf/mask.rs"),
    Label("//bazel/ebuild/private/alchemist:src/config/miscconf/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/config/miscconf/provided.rs"),
    Label("//bazel/ebuild/private/alchemist:src/config/miscconf/useflags.rs"),
    Label("//bazel/ebuild/private/alchemist:src/config/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/config/profile.rs"),
    Label("//bazel/ebuild/private/alchemist:src/config/site.rs"),
    Label("//bazel/ebuild/private/alchemist:src/data.rs"),
    Label("//bazel/ebuild/private/alchemist:src/dependency/algorithm.rs"),
    Label("//bazel/ebuild/private/alchemist:src/dependency/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/dependency/package/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/dependency/package/parser.rs"),
    Label("//bazel/ebuild/private/alchemist:src/dependency/parser/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/dependency/parser/restrict.rs"),
    Label("//bazel/ebuild/private/alchemist:src/dependency/parser/uri.rs"),
    Label("//bazel/ebuild/private/alchemist:src/dependency/restrict.rs"),
    Label("//bazel/ebuild/private/alchemist:src/dependency/uri.rs"),
    Label("//bazel/ebuild/private/alchemist:src/ebuild/ebuild_prelude.sh"),
    Label("//bazel/ebuild/private/alchemist:src/ebuild/metadata.rs"),
    Label("//bazel/ebuild/private/alchemist:src/ebuild/mod.rs"),
    Label("//bazel/ebuild/private/alchemist:src/fakechroot.rs"),
    Label("//bazel/ebuild/private/alchemist:src/fileops.rs"),
    Label("//bazel/ebuild/private/alchemist:src/lib.rs"),
    Label("//bazel/ebuild/private/alchemist:src/repository.rs"),
    Label("//bazel/ebuild/private/alchemist:src/resolver.rs"),
    Label("//bazel/ebuild/private/alchemist:src/simpleversion.rs"),
    Label("//bazel/ebuild/private/alchemist:src/testutils.rs"),
    Label("//bazel/ebuild/private/alchemist:src/toolchain/mod.rs"),
    Label("//bazel/ebuild/private/common/portage/version:Cargo.toml"),
    Label("//bazel/ebuild/private/common/portage/version:src/lib.rs"),
    Label("//bazel/ebuild/private/common/portage/version:src/version.rs"),
]
