[package]
name = "run_in_container_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
makechroot = { path = "../makechroot" }

anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
