[package]
name = "version"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
nom.workspace = true
once_cell.workspace = true
regex.workspace  = true
strum.workspace = true
strum_macros.workspace = true

[dev-dependencies]
proptest = "1.0.0"
